version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      security-updates:
        applies-to: security-updates
        patterns: ["*"]
      actions:
        applies-to: version-updates
        patterns: ["*"]
    commit-message:
      prefix: ci
    open-pull-requests-limit: 5

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    groups:
      security-updates:
        applies-to: security-updates
        patterns: ["*"]
      python:
        applies-to: version-updates
        patterns: ["*"]

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: docker
