"""Tests for the llms.txt endpoints in scripts/generate-site-content.py."""

import importlib.util
import re
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).parent.parent
DOCS_DIR = REPO_ROOT / "docs"

_SPEC = importlib.util.spec_from_file_location(
    "generate_site_content", REPO_ROOT / "scripts" / "generate-site-content.py"
)
site_content = importlib.util.module_from_spec(_SPEC)
sys.modules["generate_site_content"] = site_content
_SPEC.loader.exec_module(site_content)


# ---------------------------------------------------------------------------
# _plain_markdown
# ---------------------------------------------------------------------------


def test_tab_block_flattened_with_fence_and_blank_line():
    # docs/getting-started.md shape: fence and blank line inside a tab body.
    text = (
        '=== "macOS"\n'
        "\n"
        "    Install it:\n"
        "\n"
        "    ```bash\n"
        "    brew install skillsaw\n"
        "    ```\n"
        "\n"
        "After.\n"
    )
    result = site_content._plain_markdown(text)
    assert result == (
        "**macOS:**\n"
        "\n"
        "Install it:\n"
        "\n"
        "```bash\n"
        "brew install skillsaw\n"
        "```\n"
        "\n"
        "After.\n"
    )


def test_back_to_back_tabs():
    # A tab body ending directly at the next `=== ` marker line.
    text = '=== "pip"\n\n    pip install skillsaw\n=== "uv"\n\n    uvx skillsaw\n'
    result = site_content._plain_markdown(text)
    assert result == "**pip:**\n\npip install skillsaw\n**uv:**\n\nuvx skillsaw\n"


def test_admonition_with_table_and_icons():
    # docs/getting-started.md shape: admonition body holding a table with
    # icon shortcodes and attr lists; em dash in the title.
    text = (
        '!!! tip "Skip the manual setup — let the agent do it"\n'
        "\n"
        "    | What | Why |\n"
        "    |------|-----|\n"
        "    | :material-numeric-1-circle:{ .step-icon } | **Install** |\n"
    )
    result = site_content._plain_markdown(text)
    assert result == (
        "**Tip: Skip the manual setup — let the agent do it**\n"
        "\n"
        "| What | Why |\n"
        "|------|-----|\n"
        "| 1. | **Install** |\n"
    )


def test_bare_admonition_with_immediate_body():
    # docs/configuration.md shape: bare `!!! note`, body on the next line
    # with no blank line between.
    text = "!!! note\n    Plugin rule options work the same way.\nAfter.\n"
    result = site_content._plain_markdown(text)
    assert result == "**Note**\nPlugin rule options work the same way.\nAfter.\n"


def test_collapsible_admonition_flattened():
    # No `???` blocks exist in the corpus today; synthetic coverage for the
    # collapsible branch of the marker regex.
    text = '??? note "Details"\n    body\n'
    assert site_content._plain_markdown(text) == "**Note: Details**\nbody\n"


def test_list_indented_fence_content_preserved():
    # CommonMark allows fences indented 1-3 spaces (docs/plugins.md shape);
    # icon-like tokens inside them must not be stripped.
    text = '- item:\n\n  ```python\n  RULES = {":sparkles:"}\n  ```\n'
    assert site_content._plain_markdown(text) == text


def test_deprecated_page_admonition_multi_paragraph():
    # Generated rule-page shape: titled admonition, immediate body, and a
    # second indented paragraph after a blank line.
    text = (
        '!!! warning "Deprecated"\n'
        "    Deprecated since v0.16.0 and will be removed.\n"
        "\n"
        "    Use `agentskill-valid` instead.\n"
    )
    result = site_content._plain_markdown(text)
    assert result == (
        "**Warning: Deprecated**\n"
        "Deprecated since v0.16.0 and will be removed.\n"
        "\n"
        "Use `agentskill-valid` instead.\n"
    )


def test_plain_content_untouched_and_header_dropped():
    text = (
        "<!-- Generated by scripts/generate-site-content.py — do not edit by hand -->\n"
        "\n"
        "# Title\n"
        "\n"
        "<!-- skillsaw-disable content-weak-language -->\n"
        "\n"
        "    indented code block :sparkles: untouched\n"
        "\n"
        "Prose stays.\n"
    )
    result = site_content._plain_markdown(text)
    assert "Generated by scripts/generate-site-content" not in result
    assert "<!-- skillsaw-disable content-weak-language -->" in result
    assert "    indented code block :sparkles: untouched" in result
    assert "Prose stays." in result
    # Idempotent on already-plain text.
    assert site_content._plain_markdown(result) == result


def test_fence_state_tracking_with_nested_unclosed_fence():
    # docs/rules/content-unclosed-fence.md shape: a 4-backtick fence wrapping
    # an unclosed 3-backtick fence. Markers and icons inside are preserved;
    # a marker after the outer fence closes must still flatten.
    text = (
        "````markdown\n"
        "```bash\n"
        "echo unclosed\n"
        '=== "not a tab"\n'
        "````\n"
        "!!! note\n"
        "    body\n"
        "Then :sparkles: prose.\n"
    )
    result = site_content._plain_markdown(text)
    assert '=== "not a tab"' in result
    assert "**Note**" in result
    assert "body" in result
    assert ":sparkles:" not in result.split("````")[-1]


# ---------------------------------------------------------------------------
# guides_coverage_errors
# ---------------------------------------------------------------------------


def test_guides_cover_the_real_docs_tree():
    assert site_content.guides_coverage_errors(DOCS_DIR) == []


def test_guides_coverage_flags_unlisted_page(tmp_path):
    docs = tmp_path / "docs"
    docs.mkdir()
    for _, relpath, _ in site_content.GUIDES:
        (docs / relpath).write_text("# stub\n", encoding="utf-8")
    (docs / "scratch.md").write_text("# stray\n", encoding="utf-8")
    errors = site_content.guides_coverage_errors(docs)
    assert len(errors) == 1
    assert "docs/scratch.md" in errors[0]
    assert "NON_GUIDE_DOCS" in errors[0]


def test_guides_coverage_flags_missing_page(tmp_path):
    docs = tmp_path / "docs"
    docs.mkdir()
    for _, relpath, _ in site_content.GUIDES:
        (docs / relpath).write_text("# stub\n", encoding="utf-8")
    (docs / site_content.GUIDES[1][1]).unlink()
    errors = site_content.guides_coverage_errors(docs)
    assert len(errors) == 1
    assert "does not exist" in errors[0]
    assert site_content.GUIDES[1][1] in errors[0]


# ---------------------------------------------------------------------------
# generate_llms_txt / generate_llms_full (smoke, read-only against real docs)
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def rules_data():
    return site_content.collect_rules()


@pytest.fixture(scope="module")
def llms_txt(rules_data):
    return site_content.generate_llms_txt(rules_data)


@pytest.fixture(scope="module")
def llms_full():
    return site_content.generate_llms_full(DOCS_DIR)


def test_llms_txt_structure(llms_txt, rules_data):
    assert llms_txt.startswith("# skillsaw\n")
    assert "## Docs" in llms_txt
    assert "## Rules" in llms_txt
    assert "## Optional" in llms_txt
    assert (
        "https://raw.githubusercontent.com/stbenjam/skillsaw/main/docs/getting-started.md"
        in llms_txt
    )


def test_llms_txt_lists_every_canonical_rule_once(llms_txt, rules_data):
    urls = re.findall(r"\((https://raw\.githubusercontent\.com/[^)]+)\)", llms_txt)
    assert len(urls) == len(set(urls)), "duplicate URL in llms.txt"
    for rule_id in rules_data:
        assert "/docs/rules/{}.md".format(rule_id) in llms_txt


def test_llms_full_is_plain_markdown(llms_full):
    assert not re.search(r"^(=== |!!! |\?\?\?)", llms_full, re.MULTILINE)
    # Exact header text: a guide legitimately quotes an unrelated
    # "<!-- Generated by APM CLI ... -->" comment in inline code.
    assert "Generated by scripts/generate-site-content" not in llms_full
    assert "asciinema.org" not in llms_full
    assert "hide:" not in llms_full
    assert "{ .md-button" not in llms_full
    assert '<div class="grid' not in llms_full


def test_llms_full_covers_guides_and_rules(llms_full):
    # Assert each guide's own H1 as a heading line — nav titles are weak
    # evidence (most appear as substrings in other pages' prose).
    for _, relpath, _ in site_content.GUIDES:
        if relpath == "index.md":
            continue
        page = (DOCS_DIR / relpath).read_text(encoding="utf-8")
        h1 = re.search(r"^# (.+)$", page, re.MULTILINE)
        assert h1 is not None, "guide {} has no H1".format(relpath)
        assert re.search(
            r"^# {}$".format(re.escape(h1.group(1))), llms_full, re.MULTILINE
        ), "guide {} missing from llms-full".format(relpath)
    assert llms_full.count("\n# context-budget\n") == 1
    assert len(llms_full.encode("utf-8")) > 50_000


def test_llms_full_missing_page_fails_loud(tmp_path):
    with pytest.raises(FileNotFoundError):
        site_content.generate_llms_full(tmp_path)


def test_numeric_icons_become_numbers_and_headings_collapse():
    # :material-numeric-N-circle: carries the step number — keep it as "N.";
    # icon removal must not leave doubled spaces in headings.
    text = "## :sparkles: Onboard with AI\n"
    assert site_content._plain_markdown(text) == "## Onboard with AI\n"


def test_inpage_hrule_rewritten_to_asterisks():
    # A `---` after a blank line is a horizontal rule: rewritten to `***` so
    # `---` stays reserved for llms-full page joins. A `---` directly under
    # text is a setext heading underline and must stay untouched.
    hrule = "Some prose.\n\n---\n\nMore prose.\n"
    assert site_content._plain_markdown(hrule) == "Some prose.\n\n***\n\nMore prose.\n"
    setext = "A Heading\n---\nBody.\n"
    assert site_content._plain_markdown(setext) == setext


def test_llms_txt_marks_deprecated_and_mentions_full_file(llms_txt):
    assert "https://skillsaw.org/llms-full.txt" in llms_txt
    assert "(deprecated since v" in llms_txt
    # Group blurbs carry a flattened first sentence, not bare counts alone.
    assert re.search(r"- \[Security\]\([^)]+\): \d+ rules — ", llms_txt)


def test_write_llms_outputs_writes_both_files(tmp_path):
    # The main() wiring: both endpoint files are produced, non-empty.
    import shutil

    docs_copy = tmp_path / "docs"
    shutil.copytree(DOCS_DIR, docs_copy)
    for name in ("llms.txt", "llms-full.txt"):
        (docs_copy / name).unlink(missing_ok=True)

    site_content.write_llms_outputs(docs_copy, site_content.collect_rules())

    assert (docs_copy / "llms.txt").stat().st_size > 1_000
    assert (docs_copy / "llms-full.txt").stat().st_size > 50_000


def test_only_bare_delimiters_close_fences():
    # CommonMark: a closing fence has no info string. A ```bash line inside
    # an open fence is content — markers after it must stay untouched.
    text = (
        "```markdown\n" "```bash\n" "echo hi\n" "!!! note\n" "    body\n" "```\n" "After prose.\n"
    )
    result = site_content._plain_markdown(text)
    assert "!!! note" in result
    assert "**Note**" not in result


def test_inline_code_spans_preserved_by_noise_strip():
    # Literal Material tokens documented in inline code survive; the same
    # tokens in surrounding prose are stripped.
    line = "Use `:sparkles:` or `{ .step-icon }` markers :sparkles: here.\n"
    result = site_content._plain_markdown(line)
    assert "`:sparkles:`" in result
    assert "`{ .step-icon }`" in result
    assert result.count(":sparkles:") == 1


def test_multi_backtick_span_with_inner_backtick_preserved():
    # CommonMark: a span closes at a run of exactly the opener's length, so
    # ``literal ` and :sparkles:`` is one span — nothing inside is stripped.
    line = "Use ``literal ` and :sparkles:`` but strip :sparkles: here.\n"
    result = site_content._plain_markdown(line)
    assert "``literal ` and :sparkles:``" in result
    assert result.count(":sparkles:") == 1
    # An unmatched backtick run stays plain text and its trailing prose is
    # still stripped.
    assert site_content._plain_markdown("open `` here :brain: x\n") == "open `` here x\n"
