"""Render documentation as Markdown."""

from __future__ import annotations

import hashlib
import json
from typing import Dict, List

from skillsaw.docs.models import (
    AgentDoc,
    CommandDoc,
    DocsOutput,
    HookDoc,
    McpServerDoc,
    PluginDoc,
    RuleFileDoc,
    SkillDoc,
    name_str,
)


def render_markdown(docs: DocsOutput) -> Dict[str, str]:
    """Render documentation as Markdown files.

    Returns a dict of {filename: markdown_content}.
    Marketplaces get an index + per-plugin files; others get a single index.
    """
    # Gated on the model, not the primary type. A Codex catalog in a repo
    # that is also APM or dot-claude loses the primary-type slot to those,
    # and the single-page renderer shows only plugins[0].
    if docs.marketplace:
        return _render_marketplace(docs)
    return {"README.md": _render_single_page(docs)}


def _render_single_page(docs: DocsOutput) -> str:
    lines: List[str] = []
    if docs.title:
        lines += [f"# {docs.title}", ""]
    plugin = docs.plugins[0] if docs.plugins else None

    if plugin:
        _append_plugin_meta(lines, plugin)
        _append_plugin_sections(lines, plugin)

    if docs.skills:
        _append_skills_section(lines, docs.skills)

    lines.append("")
    lines.append("---")
    lines.append("*Generated by [skillsaw](https://github.com/stbenjam/skillsaw)*")
    return "\n".join(lines) + "\n"


def _render_marketplace(docs: DocsOutput) -> Dict[str, str]:
    mp = docs.marketplace
    assert mp is not None
    pages: Dict[str, str] = {}

    sorted_plugins = sorted(mp.plugins, key=lambda p: name_str(p.name).lower())
    # Sanitising is lossy — "a/b", "a\\b" and "a:b" all reduce to "a-b" —
    # and pages are keyed by filename, so without this a later plugin
    # silently replaces an earlier one's page while both index rows link
    # to the survivor. Names are only warned about, never rejected.
    filenames = _unique_filenames(sorted_plugins)

    # Index
    lines: List[str] = [f"# {mp.name or docs.title}", ""]
    if mp.owner and mp.owner.get("name"):
        lines.append(f"**Owner:** {mp.owner['name']}")
        lines.append("")

    total_cmds = sum(len(p.commands) for p in sorted_plugins)
    total_skills = sum(len(p.skills) for p in sorted_plugins)
    lines.append(
        f"**{len(sorted_plugins)}** plugins | **{total_cmds}** commands | **{total_skills}** skills"
    )
    lines.append("")

    lines.append("## Plugins")
    lines.append("")
    lines.append("| Plugin | Description | Version |")
    lines.append("|--------|-------------|---------|")
    for plugin in sorted_plugins:
        fname = filenames[id(plugin)]
        label = _table_cell(plugin.display_name or plugin.name)
        desc = _table_cell(plugin.description or "-")
        ver = _table_cell(plugin.version or "-")
        lines.append(f"| [{label}]({fname}) | {desc} | {ver} |")
    lines.append("")

    lines.append("---")
    lines.append("*Generated by [skillsaw](https://github.com/stbenjam/skillsaw)*")
    pages["README.md"] = "\n".join(lines) + "\n"

    # Per-plugin pages
    for plugin in sorted_plugins:
        fname = filenames[id(plugin)]
        heading = plugin.display_name or plugin.name
        plines: List[str] = [f"# {heading}", ""]
        plines.append(f"[&larr; Back to {mp.name or 'index'}](README.md)")
        plines.append("")
        _append_plugin_meta(plines, plugin)
        _append_plugin_sections(plines, plugin)
        plines.append("")
        plines.append("---")
        plines.append("*Generated by [skillsaw](https://github.com/stbenjam/skillsaw)*")
        pages[fname] = "\n".join(plines) + "\n"

    return pages


def _table_cell(value: object) -> str:
    """Make catalog metadata safe for a Markdown table cell."""
    return " ".join(str(value).splitlines()).replace("|", r"\|")


# -- Plugin content --


def _append_plugin_meta(lines: List[str], plugin: PluginDoc) -> None:
    if plugin.description:
        lines.append(f"> {plugin.description}")
        lines.append("")
    meta = []
    if plugin.version:
        meta.append(f"**Version:** {plugin.version}")
    if plugin.author and plugin.author.get("name"):
        meta.append(f"**Author:** {plugin.author['name']}")
    if plugin.license:
        meta.append(f"**License:** {plugin.license}")
    if plugin.category:
        meta.append(f"**Category:** {plugin.category}")
    if meta:
        lines.append(" | ".join(meta))
        lines.append("")
    link_parts = []
    if plugin.homepage:
        link_parts.append(f"[Homepage]({plugin.homepage})")
    if plugin.repository:
        link_parts.append(f"[Repository]({plugin.repository})")
    if link_parts:
        lines.append(" | ".join(link_parts))
        lines.append("")
    all_tags = (plugin.tags or []) + (plugin.keywords or [])
    if all_tags:
        lines.append("**Tags:** " + ", ".join(f"`{t}`" for t in all_tags))
        lines.append("")


def _append_plugin_sections(lines: List[str], plugin: PluginDoc) -> None:
    if plugin.commands:
        lines.append("## Commands")
        lines.append("")
        for cmd in plugin.commands:
            _append_command(lines, cmd)

    if plugin.skills:
        _append_skills_section(lines, plugin.skills)

    if plugin.agents:
        lines.append("## Agents")
        lines.append("")
        for agent in plugin.agents:
            _append_agent(lines, agent)

    if plugin.hooks:
        lines.append("## Hooks")
        lines.append("")
        for hook in plugin.hooks:
            _append_hook(lines, hook)

    if plugin.mcp_servers:
        lines.append("## MCP Servers")
        lines.append("")
        _append_mcp_table(lines, plugin.mcp_servers)

    if plugin.rules:
        lines.append("## Rules")
        lines.append("")
        for rule in plugin.rules:
            _append_rule(lines, rule)


# -- Individual content renderers --


def _append_command(lines: List[str], cmd: CommandDoc) -> None:
    title = f"### {cmd.name}"
    if cmd.full_name:
        title += f" (`{cmd.full_name}`)"
    lines.append(title)
    lines.append("")
    if cmd.description:
        lines.append(cmd.description)
        lines.append("")
    if cmd.synopsis:
        lines.append("```")
        lines.append(cmd.synopsis)
        lines.append("```")
        lines.append("")
    if cmd.body:
        lines.append(cmd.body)
        lines.append("")


def _append_skills_section(lines: List[str], skills: List[SkillDoc]) -> None:
    lines.append("## Skills")
    lines.append("")
    for skill in sorted(skills, key=lambda s: name_str(s.name).lower()):
        lines.append(f"### {skill.name}")
        lines.append("")
        if skill.description:
            lines.append(skill.description)
            lines.append("")
        meta = []
        if skill.license:
            meta.append(f"**License:** {skill.license}")
        if skill.compatibility:
            meta.append(f"**Compatibility:** {skill.compatibility}")
        if skill.allowed_tools:
            meta.append(f"**Allowed tools:** {', '.join(skill.allowed_tools)}")
        if meta:
            lines.append(" | ".join(meta))
            lines.append("")


def _append_agent(lines: List[str], agent: AgentDoc) -> None:
    lines.append(f"### {agent.name}")
    lines.append("")
    if agent.description:
        lines.append(agent.description)
        lines.append("")


def _append_hook(lines: List[str], hook: HookDoc) -> None:
    lines.append(f"### {hook.event_type}")
    lines.append("")
    for entry in hook.entries:
        lines.append(f"**Matcher:** `{entry.matcher}`")
        lines.append("")
        lines.append("```json")
        lines.append(json.dumps(entry.hooks, indent=2))
        lines.append("```")
        lines.append("")


def _append_mcp_table(lines: List[str], servers: List[McpServerDoc]) -> None:
    lines.append("| Name | Type | Endpoint | Source |")
    lines.append("|------|------|----------|--------|")
    for srv in servers:
        endpoint = srv.config.get("command", srv.config.get("url", ""))
        lines.append(f"| {srv.name} | `{srv.server_type}` | `{endpoint}` | {srv.source_file} |")
    lines.append("")


def _append_rule(lines: List[str], rule: RuleFileDoc) -> None:
    lines.append(f"### {rule.name}")
    lines.append("")
    desc = rule.description or (rule.body[:200] if rule.body else "")
    if desc:
        lines.append(desc)
        lines.append("")
    if rule.globs:
        lines.append(f"**Paths:** {', '.join(f'`{g}`' for g in rule.globs)}")
        lines.append("")


# -- Utilities --


# Anything that could steer a filename out of the output directory on any
# platform: both separators, the drive-letter colon, and the parent link.
# A kebab-case violation is only a warning, so `docs` must not rely on
# `lint` having rejected the name first.
# 255 bytes is the near-universal component limit (ext4, APFS, NTFS).
# The ".md" suffix and any "-2" the allocator appends have to fit too.
_MAX_STEM_BYTES = 240

_WINDOWS_RESERVED_NAMES = {"con", "prn", "aux", "nul"} | {
    f"{stem}{n}" for stem in ("com", "lpt") for n in range(1, 10)
}

_UNSAFE_FILENAME_CHARS = str.maketrans({c: "-" for c in '/\\:<>"|?*'})


def _unique_filenames(plugins: List[PluginDoc]) -> Dict[int, str]:
    """One distinct page filename per plugin, keyed by object identity."""
    # Reserved case-folded: "Foo.md" and "foo.md" are one file on default
    # macOS and Windows installs, so an exact-case set would hand out both
    # and the second page would overwrite the first. The chosen spelling is
    # still what gets written.
    # Seeded with the index page: a plugin named "readme" otherwise takes
    # "README.md" and the index overwrites it, losing that plugin's page
    # and every link to it.
    used: set = {"readme.md"}
    out: Dict[int, str] = {}
    for plugin in plugins:
        candidate = _plugin_filename(plugin)
        if candidate.casefold() in used:
            # Probing rather than counting: a generated "a-b-2.md" can
            # collide with a plugin genuinely named "a-b-2", so every name
            # handed out has to be reserved and the next one re-checked.
            stem = candidate[:-3] if candidate.endswith(".md") else candidate
            n = 2
            while f"{stem}-{n}.md".casefold() in used:
                n += 1
            candidate = f"{stem}-{n}.md"
        used.add(candidate.casefold())
        out[id(plugin)] = candidate
    return out


def _plugin_filename(plugin: PluginDoc) -> str:
    # ``plugin.name`` is manifest-derived and may be a non-string (e.g. a
    # numeric ``"name": 123`` in marketplace.json); coerce before calling
    # string methods so ``docs`` doesn't crash on inputs ``lint`` tolerates.
    # It is also untrusted: a plugin named ``..\..\evil`` or ``C:\temp``
    # would otherwise resolve outside the requested output directory when
    # the caller joins it, and on Windows ``\`` is a real separator.
    safe = name_str(plugin.name).translate(_UNSAFE_FILENAME_CHARS).replace(" ", "-")
    safe = safe.replace("..", "-").strip(".-") or "plugin"
    if len(safe.encode("utf-8")) > _MAX_STEM_BYTES:
        # A kebab-case name longer than the filesystem's component limit is
        # valid to codex-plugin-json-valid but unwritable: write_text()
        # raises ENAMETOOLONG and documentation generation dies for the
        # whole catalog. The digest keeps distinct long names distinct; the
        # allocator's own probing still resolves any collision it creates.
        digest = hashlib.sha256(safe.encode("utf-8")).hexdigest()[:12]
        head = safe.encode("utf-8")[: _MAX_STEM_BYTES - len(digest) - 1].decode("utf-8", "ignore")
        safe = f"{head}-{digest}"
    if safe.casefold() in _WINDOWS_RESERVED_NAMES:
        # `con`, `nul`, `com1` and friends stay reserved even with an
        # extension, so `con.md` cannot be created on Windows at all and
        # documentation generation fails for the whole catalog.
        safe = f"{safe}-plugin"
    return f"{safe}.md"
