"""Render documentation as Markdown."""

from __future__ import annotations

import json
from typing import Dict, List

from skillsaw.context import RepositoryType
from skillsaw.docs.models import (
    AgentDoc,
    CommandDoc,
    DocsOutput,
    HookDoc,
    McpServerDoc,
    PluginDoc,
    RuleFileDoc,
    SkillDoc,
)


def render_markdown(docs: DocsOutput) -> Dict[str, str]:
    """Render documentation as Markdown files.

    Returns a dict of {filename: markdown_content}.
    Marketplaces get an index + per-plugin files; others get a single index.
    """
    if docs.repo_type == RepositoryType.MARKETPLACE and docs.marketplace:
        return _render_marketplace(docs)
    return {"README.md": _render_single_page(docs)}


def _render_single_page(docs: DocsOutput) -> str:
    lines: List[str] = []
    if docs.title:
        lines += [f"# {docs.title}", ""]
    plugin = docs.plugins[0] if docs.plugins else None

    if plugin:
        _append_plugin_meta(lines, plugin)
        _append_plugin_sections(lines, plugin)

    if docs.skills:
        _append_skills_section(lines, docs.skills)

    lines.append("")
    lines.append("---")
    lines.append("*Generated by [skillsaw](https://github.com/stbenjam/skillsaw)*")
    return "\n".join(lines) + "\n"


def _render_marketplace(docs: DocsOutput) -> Dict[str, str]:
    mp = docs.marketplace
    assert mp is not None
    pages: Dict[str, str] = {}

    sorted_plugins = sorted(mp.plugins, key=lambda p: p.name.lower())

    # Index
    lines: List[str] = [f"# {mp.name or docs.title}", ""]
    if mp.owner and mp.owner.get("name"):
        lines.append(f"**Owner:** {mp.owner['name']}")
        lines.append("")

    total_cmds = sum(len(p.commands) for p in sorted_plugins)
    total_skills = sum(len(p.skills) for p in sorted_plugins)
    lines.append(
        f"**{len(sorted_plugins)}** plugins | **{total_cmds}** commands | **{total_skills}** skills"
    )
    lines.append("")

    lines.append("## Plugins")
    lines.append("")
    lines.append("| Plugin | Description | Version |")
    lines.append("|--------|-------------|---------|")
    for plugin in sorted_plugins:
        fname = _plugin_filename(plugin)
        desc = plugin.description or "-"
        ver = plugin.version or "-"
        lines.append(f"| [{plugin.name}]({fname}) | {desc} | {ver} |")
    lines.append("")

    lines.append("---")
    lines.append("*Generated by [skillsaw](https://github.com/stbenjam/skillsaw)*")
    pages["README.md"] = "\n".join(lines) + "\n"

    # Per-plugin pages
    for plugin in sorted_plugins:
        fname = _plugin_filename(plugin)
        plines: List[str] = [f"# {plugin.name}", ""]
        plines.append(f"[&larr; Back to {mp.name or 'index'}](README.md)")
        plines.append("")
        _append_plugin_meta(plines, plugin)
        _append_plugin_sections(plines, plugin)
        plines.append("")
        plines.append("---")
        plines.append("*Generated by [skillsaw](https://github.com/stbenjam/skillsaw)*")
        pages[fname] = "\n".join(plines) + "\n"

    return pages


# -- Plugin content --


def _append_plugin_meta(lines: List[str], plugin: PluginDoc) -> None:
    if plugin.description:
        lines.append(f"> {plugin.description}")
        lines.append("")
    meta = []
    if plugin.version:
        meta.append(f"**Version:** {plugin.version}")
    if plugin.author and plugin.author.get("name"):
        meta.append(f"**Author:** {plugin.author['name']}")
    if meta:
        lines.append(" | ".join(meta))
        lines.append("")


def _append_plugin_sections(lines: List[str], plugin: PluginDoc) -> None:
    if plugin.commands:
        lines.append("## Commands")
        lines.append("")
        for cmd in plugin.commands:
            _append_command(lines, cmd)

    if plugin.skills:
        _append_skills_section(lines, plugin.skills)

    if plugin.agents:
        lines.append("## Agents")
        lines.append("")
        for agent in plugin.agents:
            _append_agent(lines, agent)

    if plugin.hooks:
        lines.append("## Hooks")
        lines.append("")
        for hook in plugin.hooks:
            _append_hook(lines, hook)

    if plugin.mcp_servers:
        lines.append("## MCP Servers")
        lines.append("")
        _append_mcp_table(lines, plugin.mcp_servers)

    if plugin.rules:
        lines.append("## Rules")
        lines.append("")
        for rule in plugin.rules:
            _append_rule(lines, rule)


# -- Individual content renderers --


def _append_command(lines: List[str], cmd: CommandDoc) -> None:
    title = f"### {cmd.name}"
    if cmd.full_name:
        title += f" (`{cmd.full_name}`)"
    lines.append(title)
    lines.append("")
    if cmd.description:
        lines.append(cmd.description)
        lines.append("")
    if cmd.synopsis:
        lines.append("```")
        lines.append(cmd.synopsis)
        lines.append("```")
        lines.append("")
    if cmd.body:
        lines.append(cmd.body)
        lines.append("")


def _append_skills_section(lines: List[str], skills: List[SkillDoc]) -> None:
    lines.append("## Skills")
    lines.append("")
    for skill in sorted(skills, key=lambda s: s.name.lower()):
        lines.append(f"### {skill.name}")
        lines.append("")
        if skill.description:
            lines.append(skill.description)
            lines.append("")
        meta = []
        if skill.license:
            meta.append(f"**License:** {skill.license}")
        if skill.compatibility:
            meta.append(f"**Compatibility:** {skill.compatibility}")
        if skill.allowed_tools:
            meta.append(f"**Allowed tools:** {', '.join(skill.allowed_tools)}")
        if meta:
            lines.append(" | ".join(meta))
            lines.append("")


def _append_agent(lines: List[str], agent: AgentDoc) -> None:
    lines.append(f"### {agent.name}")
    lines.append("")
    if agent.description:
        lines.append(agent.description)
        lines.append("")


def _append_hook(lines: List[str], hook: HookDoc) -> None:
    lines.append(f"### {hook.event_type}")
    lines.append("")
    for entry in hook.entries:
        lines.append(f"**Matcher:** `{entry.matcher}`")
        lines.append("")
        lines.append("```json")
        lines.append(json.dumps(entry.hooks, indent=2))
        lines.append("```")
        lines.append("")


def _append_mcp_table(lines: List[str], servers: List[McpServerDoc]) -> None:
    lines.append("| Name | Type | Endpoint | Source |")
    lines.append("|------|------|----------|--------|")
    for srv in servers:
        endpoint = srv.config.get("command", srv.config.get("url", ""))
        lines.append(f"| {srv.name} | `{srv.server_type}` | `{endpoint}` | {srv.source_file} |")
    lines.append("")


def _append_rule(lines: List[str], rule: RuleFileDoc) -> None:
    lines.append(f"### {rule.name}")
    lines.append("")
    desc = rule.description or (rule.body[:200] if rule.body else "")
    if desc:
        lines.append(desc)
        lines.append("")
    if rule.globs:
        lines.append(f"**Paths:** {', '.join(f'`{g}`' for g in rule.globs)}")
        lines.append("")


# -- Utilities --


def _plugin_filename(plugin: PluginDoc) -> str:
    safe = plugin.name.replace("/", "-").replace(" ", "-")
    return f"{safe}.md"
