"""
Rule: claude-md-agents-import
"""

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Set, Tuple

from skillsaw.blocks import AgentsMdBlock, ClaudeMdBlock
from skillsaw.context import RepositoryContext, RepositoryType
from skillsaw.paths import safe_resolve
from skillsaw.rule import (
    AutofixConfidence,
    AutofixResult,
    Rule,
    RuleViolation,
    Severity,
)
from skillsaw.utils import has_generated_marker, read_text

from ._helpers import iter_instruction_imports, iter_markdown_instruction_imports

#: How a pointer stub defers to CLAUDE.md: "See CLAUDE.md", "all rules are
#: maintained in CLAUDE.md", "this file is a pointer". A line that merely
#: names the file ("keep CLAUDE.md synchronized") does not match.
_DEFERRAL_RE = re.compile(
    r"\b(?:see|read|refer(?:s)? to|follow|consult|use|open|check|maintained in|"
    r"lives? in|kept in|defined in|documented in|found in|source of truth|"
    r"single (?:source|place)|pointer|not a (?:second )?copy|instead)\b",
    re.IGNORECASE,
)
#: "Do not use CLAUDE.md; follow the instructions here" rejects CLAUDE.md
#: with the same verb a deferral uses. "This file is a pointer, not a second
#: copy" is the one negation that is itself a deferral, so it is removed
#: before the negation check.
_NEGATION_RE = re.compile(
    r"\b(?:not|never|don'?t|no longer|instead of|rather than|ignore|avoid)\b",
    re.IGNORECASE,
)
_NOT_A_COPY_RE = re.compile(r"\bnot a (?:second )?(?:copy|duplicate)\b", re.IGNORECASE)


@dataclass
class _BodyShape:
    """What a CLAUDE.md body holds once blank lines and comments are ignored.

    ``import_lines`` contain a prose ``@`` import of the sibling AGENTS.md;
    ``extra_lines`` carry anything beyond a standalone import — prose,
    headings, code fences, or other imports.
    """

    import_lines: List[int] = field(default_factory=list)
    extra_lines: List[int] = field(default_factory=list)


class ClaudeMdAgentsImportRule(Rule):
    """Recommend that a CLAUDE.md sitting next to an AGENTS.md import it.

    Claude Code reads CLAUDE.md; almost every other agent reads AGENTS.md.
    Teams that keep both end up maintaining two copies of the same
    instructions, and the copies drift (which is what
    ``content-instruction-drift`` reports once it has happened). Claude
    Code's ``@path`` import syntax removes the duplication instead of
    policing it. Claude-specific instructions may follow the import without
    duplicating the shared guidance.

    Deliberately INFO: importing shared guidance is a maintainability
    recommendation, not a correctness requirement.
    """

    repo_types = frozenset({RepositoryType.CLAUDE_MD, RepositoryType.AGENTS_MD})
    default_enabled = "auto"
    since = "0.20.0"
    autofix_confidence = AutofixConfidence.SUGGEST

    config_schema = {
        "allow-extra": {
            "type": "bool",
            "default": True,
            "description": (
                "Allow Claude-specific content in CLAUDE.md when it also imports "
                "the sibling AGENTS.md"
            ),
        },
        "ignore-generated": {
            "type": "bool",
            "default": True,
            "description": (
                "Skip a CLAUDE.md carrying a generated-file marker (e.g. APM's "
                "'Generated by APM CLI' header) — a compiled file cannot be "
                "hand-replaced with an import"
            ),
        },
    }

    @property
    def rule_id(self) -> str:
        return "claude-md-agents-import"

    @property
    def description(self) -> str:
        return (
            "CLAUDE.md next to an AGENTS.md should import it so both assistants "
            "read one source of truth"
        )

    def default_severity(self) -> Severity:
        return Severity.INFO

    # -- pairing ---------------------------------------------------------

    @staticmethod
    def _pairs(
        context: RepositoryContext,
    ) -> List[Tuple[ClaudeMdBlock, AgentsMdBlock]]:
        """Every (CLAUDE.md, AGENTS.md) pair sharing a directory.

        ``content-instruction-drift`` compares instruction files pairwise
        across the whole repository rather than pairing them per directory,
        so there is no existing pairing helper to reuse. Both files are
        discovered per directory by the same walk, so the tree already holds
        everything needed: group the two block types on their resolved
        parent directory.

        A CLAUDE.md that is a *symlink* to its AGENTS.md is never a pair:
        it is the other honest answer to the duplication problem (one file,
        two names), and the two blocks share a resolved path. The lint tree
        already dedupes on resolved path, so such a CLAUDE.md usually never
        reaches a rule at all — the check here states the intent rather
        than relying on that.
        """
        agents_by_dir: Dict[Path, AgentsMdBlock] = {}
        for block in context.lint_tree.find(AgentsMdBlock):
            parent = safe_resolve(block.path.parent)
            if parent is None:
                continue
            agents_by_dir.setdefault(parent, block)

        pairs: List[Tuple[ClaudeMdBlock, AgentsMdBlock]] = []
        for block in context.lint_tree.find(ClaudeMdBlock):
            parent = safe_resolve(block.path.parent)
            if parent is None:
                continue
            agents = agents_by_dir.get(parent)
            if agents is None or agents.resolved_path == block.resolved_path:
                continue
            pairs.append((block, agents))
        pairs.sort(key=lambda pair: str(pair[0].path))
        return pairs

    # -- body shape ------------------------------------------------------

    @staticmethod
    def _is_sibling_import(
        target: str,
        base: Path,
        agents_resolved: Optional[Path],
    ) -> bool:
        """Whether *target* resolves to the paired sibling AGENTS.md."""
        if agents_resolved is None:
            return False
        # ``@~/...`` is Claude Code's machine-local memory syntax — it can
        # never name a file inside this repository.
        if not target or target.startswith("~"):
            return False
        resolved = safe_resolve(base / target)
        return resolved is not None and resolved == agents_resolved

    def _shape(self, block: ClaudeMdBlock, agents_resolved: Optional[Path]) -> _BodyShape:
        """Record sibling imports and strict-mode extras in *block*.

        Blank lines and HTML comments never count as content. In strict mode,
        everything else beyond a standalone import does — headings, prose,
        code fences, indented code, wrappers, and a second import. Import
        recognition uses prose from the Markdown AST, so examples in code or
        comments cannot satisfy the rule.
        """
        body = block.read_body(strip_code_blocks=False) or ""
        raw = body.splitlines()
        doc = block.markdown
        # prose_lines() blanks HTML comments *and* code spans and empties
        # fence lines; only the comment blanking makes a line ignorable, so
        # the comment ranges say which blanked lines to drop.
        prose = [text for _file_line, text in doc.prose_lines()]
        comment_lines: Set[int] = set()
        for comment in doc.html_comments():
            comment_lines.update(range(comment.body_line_start, comment.body_line_end + 1))

        base = block.path.parent
        shape = _BodyShape()
        sibling_import_lines = {
            import_ref.body_line
            for import_ref in iter_markdown_instruction_imports(doc)
            if self._is_sibling_import(import_ref.path, base, agents_resolved)
        }
        for index, line in enumerate(raw):
            if not line.strip():
                continue
            body_line = index + 1
            blanked = index < len(prose) and not prose[index].strip()
            if blanked and body_line in comment_lines:
                continue
            sibling_import = body_line in sibling_import_lines
            if sibling_import:
                shape.import_lines.append(body_line)

            raw_imports = list(iter_instruction_imports(line))
            import_only = (
                len(raw_imports) == 1
                and sibling_import
                and self._is_sibling_import(raw_imports[0][0], base, agents_resolved)
                and not line[: raw_imports[0][1]].strip()
                and not line[raw_imports[0][2] :].strip()
            )
            if not import_only:
                shape.extra_lines.append(body_line)
        return shape

    @staticmethod
    def _normalized(body: Optional[str]) -> List[str]:
        """Body lines with trailing whitespace stripped — the identity test.

        Anything finer than trailing whitespace is byte-meaningful: if the
        two files differ at all, replacing one with an import is a content
        decision a linter must not make on its own.
        """
        return [line.rstrip() for line in (body or "").splitlines()]

    def _is_duplicate(self, claude_body: Optional[str], agents_body: Optional[str]) -> bool:
        claude_lines = self._normalized(claude_body)
        return bool(claude_lines) and claude_lines == self._normalized(agents_body)

    #: An AGENTS.md this short that names CLAUDE.md is a pointer, not a
    #: second copy: "See CLAUDE.md for all project rules."
    _POINTER_MAX_PROSE_LINES = 12

    def _agents_points_at_claude(self, agents: AgentsMdBlock, claude: ClaudeMdBlock) -> bool:
        """Whether the pair already has one source of truth — in CLAUDE.md.

        The reverse arrangement: AGENTS.md imports ``@CLAUDE.md``, or is a
        short stub that names CLAUDE.md and defers to it. Either way the
        team already made the choice this rule recommends, in the other
        direction, and telling CLAUDE.md to import AGENTS.md would create a
        cycle.
        """
        claude_resolved = claude.resolved_path
        if claude_resolved is None:
            return False
        doc = agents.markdown
        base = agents.path.parent
        for import_ref in iter_markdown_instruction_imports(doc):
            if self._is_sibling_import(import_ref.path, base, claude_resolved):
                return True
        # Raw lines, not prose_lines(): a stub names the file in a code span
        # (`CLAUDE.md`) as often as in plain text, and prose blanking would
        # hide it. A bare mention is not enough — "keep CLAUDE.md in sync"
        # is the opposite of deferring to it — so the line must also read
        # as a deferral.
        body = agents.read_body(strip_code_blocks=False) or ""
        lines = [line for line in body.splitlines() if line.strip()]
        if len(lines) > self._POINTER_MAX_PROSE_LINES:
            return False
        return any(
            "CLAUDE.md" in line
            and _DEFERRAL_RE.search(line)
            and not _NEGATION_RE.search(_NOT_A_COPY_RE.sub("", line))
            for line in lines
        )

    # -- check -----------------------------------------------------------

    def check(self, context: RepositoryContext) -> List[RuleViolation]:
        pairs = self._pairs(context)
        if not pairs:
            return []
        allow_extra = bool(self.setting("allow-extra"))
        ignore_generated = bool(self.setting("ignore-generated"))

        violations: List[RuleViolation] = []
        for claude, agents in pairs:
            body = claude.read_body(strip_code_blocks=False)
            if not body or not body.strip():
                # An empty CLAUDE.md is ``instruction-file-valid``'s finding,
                # and there is no content to move anywhere.
                continue
            if ignore_generated and has_generated_marker(body):
                continue
            if self._agents_points_at_claude(agents, claude):
                continue

            shape = self._shape(claude, agents.resolved_path)
            if not shape.extra_lines:
                # Already the recommended end state (or comments only).
                continue
            if allow_extra and shape.import_lines:
                continue

            is_duplicate = self._is_duplicate(
                body,
                agents.read_body(strip_code_blocks=False),
            )
            if shape.import_lines:
                message = (
                    "CLAUDE.md imports AGENTS.md but also carries its own "
                    "instructions — move them into AGENTS.md so the import is the "
                    "whole file and both assistants read one source of truth"
                )
            elif is_duplicate:
                message = (
                    "CLAUDE.md duplicates its sibling AGENTS.md — replace its contents "
                    "with '@AGENTS.md' so both assistants read one source of truth"
                )
            elif allow_extra:
                message = (
                    "CLAUDE.md does not import its sibling AGENTS.md — add '@AGENTS.md', "
                    "remove any duplicated shared guidance, and keep Claude-specific "
                    "instructions below the import"
                )
            else:
                message = (
                    "CLAUDE.md does not import its sibling AGENTS.md — move any "
                    "instructions that must be kept into AGENTS.md, then make CLAUDE.md "
                    "the single line '@AGENTS.md'"
                )
            violations.append(
                self.violation(
                    message,
                    block=claude,
                    line=shape.extra_lines[0],
                    fixable=is_duplicate,
                )
            )
        return violations

    # -- fix -------------------------------------------------------------

    def fix(
        self, context: RepositoryContext, violations: List[RuleViolation]
    ) -> List[AutofixResult]:
        """Replace a CLAUDE.md that is a byte-for-byte copy with the import.

        Restructuring a whole file is a judgment call, so this is a SUGGEST
        fix and applies only when the two bodies are identical after
        trailing-whitespace normalization — then the import provably loses
        nothing. Unlike a splice, it changes the file's line count by
        design.
        """
        agents_by_claude = {claude.resolved_path: agents for claude, agents in self._pairs(context)}
        results: List[AutofixResult] = []
        fixed: Set[Path] = set()
        for violation in violations:
            if violation.file_path is None:
                continue
            resolved = safe_resolve(violation.file_path) or violation.file_path
            if resolved in fixed:
                continue
            agents = agents_by_claude.get(resolved)
            if agents is None:
                continue
            content = read_text(violation.file_path)
            if content is None:
                continue
            if not self._is_duplicate(content, agents.read_body(strip_code_blocks=False)):
                continue
            replacement = f"@{agents.path.name}\n"
            if content == replacement:
                continue
            fixed.add(resolved)
            results.append(
                AutofixResult(
                    rule_id=self.rule_id,
                    file_path=violation.file_path,
                    confidence=AutofixConfidence.SUGGEST,
                    original_content=content,
                    fixed_content=replacement,
                    description=(
                        f"Replace the duplicated CLAUDE.md body with " f"'@{agents.path.name}'"
                    ),
                    violations_fixed=[violation],
                )
            )
        return results
