"""Content instruction drift rule"""

import re
from dataclasses import dataclass, field
from difflib import SequenceMatcher
from typing import Any, Dict, List

from skillsaw.rule import Rule, RuleViolation, Severity
from skillsaw.context import RepositoryContext
from skillsaw.blocks import ContentBlock
from skillsaw.rules.builtin.content_analysis import (
    gather_all_content_blocks,
)

# Categories of instruction files that get copied between assistants
# (CLAUDE.md <-> AGENTS.md <-> copilot-instructions.md <-> rules files).
_INSTRUCTION_CATEGORIES = ("claude-md", "agents-md", "gemini-md", "instruction", "rule")

# Files carrying a generated-file marker are compiled outputs (e.g. apm
# compiles one source into CLAUDE.md, copilot-instructions.md, ...).
# Their near-copies are by design, not drift.  Matched forms: the generic
# "generated by ... do not edit" wording, and APM's actual header stamp —
# apm writes only '<!-- Generated by APM CLI from .apm/ primitives -->'
# on .github/copilot-instructions.md and .github/instructions/*, with no
# "do not edit" text anywhere in the file.
_GENERATED_MARKER = re.compile(
    r"generated by .*(?:do not edit|don't edit)" r"|do not edit manually" r"|generated by apm cli",
    re.IGNORECASE,
)


@dataclass
class _Section:
    """A leaf markdown section prepared for cross-file comparison."""

    block: ContentBlock = field(repr=False)
    heading: str
    body_line: int
    words: List[str] = field(repr=False)


class ContentInstructionDriftRule(Rule):
    """Detect near-duplicate sections that drifted apart across instruction files"""

    formats = None
    since = "0.17.0"

    MIN_FILES = 2

    _DEFAULT_THRESHOLD = 0.8
    _DEFAULT_MIN_WORDS = 40
    _DEFAULT_MAX_SECTIONS = 400

    config_schema = {
        "similarity-threshold": {
            "type": "float",
            "default": _DEFAULT_THRESHOLD,
            "description": (
                "Similarity ratio (0-1, exclusive) above which two sections in "
                "different instruction files are considered drifted copies; "
                "identical sections never fire"
            ),
        },
        "min-section-words": {
            "type": "int",
            "default": _DEFAULT_MIN_WORDS,
            "description": (
                "Minimum number of words a section must contain to participate "
                "in drift comparison"
            ),
        },
        "ignore-generated": {
            "type": "bool",
            "default": True,
            "description": (
                "Skip files carrying a generated-file marker (e.g. 'generated "
                "by ... do not edit', APM's 'Generated by APM CLI' header) — "
                "compiled instruction files are near-copies by design"
            ),
        },
        "similarity-max-sections": {
            "type": "int",
            "default": _DEFAULT_MAX_SECTIONS,
            "description": (
                "Maximum number of qualifying sections compared pairwise; "
                "sections beyond the cap (in file-path order) are skipped, "
                "bounding the quadratic comparison on degenerate inputs"
            ),
        },
    }

    def __init__(self, config: Dict[str, Any] = None):
        super().__init__(config)
        threshold = self.config.get("similarity-threshold", self._DEFAULT_THRESHOLD)
        if not isinstance(threshold, (int, float)) or isinstance(threshold, bool):
            raise ValueError(
                f"'similarity-threshold' for rule '{self.rule_id}' must be a "
                f"number, got {type(threshold).__name__}"
            )
        if not 0 < threshold < 1:
            raise ValueError(
                f"'similarity-threshold' for rule '{self.rule_id}' must be "
                f"greater than 0 and less than 1, got {threshold}"
            )
        self._threshold = float(threshold)

        min_words = self.config.get("min-section-words", self._DEFAULT_MIN_WORDS)
        if not isinstance(min_words, int) or isinstance(min_words, bool):
            raise ValueError(
                f"'min-section-words' for rule '{self.rule_id}' must be an "
                f"integer, got {type(min_words).__name__}"
            )
        if min_words < 1:
            raise ValueError(
                f"'min-section-words' for rule '{self.rule_id}' must be at "
                f"least 1, got {min_words}"
            )
        self._min_words = min_words
        self._ignore_generated = bool(self.config.get("ignore-generated", True))

        max_sections = self.config.get("similarity-max-sections", self._DEFAULT_MAX_SECTIONS)
        if not isinstance(max_sections, int) or isinstance(max_sections, bool):
            raise ValueError(
                f"'similarity-max-sections' for rule '{self.rule_id}' must be "
                f"an integer, got {type(max_sections).__name__}"
            )
        if max_sections < 2:
            raise ValueError(
                f"'similarity-max-sections' for rule '{self.rule_id}' must be "
                f"at least 2, got {max_sections}"
            )
        self._max_sections = max_sections

    @property
    def rule_id(self) -> str:
        return "content-instruction-drift"

    @property
    def description(self) -> str:
        return "Detect near-duplicate sections that have drifted apart across instruction files"

    def default_severity(self) -> Severity:
        return Severity.INFO

    def _extract_sections(self, cf: ContentBlock) -> List[_Section]:
        """Slice a block's body into leaf sections, one per heading.

        A section runs from the line after its heading to the next heading of
        ANY level (or EOF). The preamble before the first heading is skipped,
        and heading text is excluded from the compared words so a retitled but
        otherwise identical section still reads as identical.
        """
        body = cf.read_body()
        if not body:
            return []
        headings = cf.markdown.headings()
        if not headings:
            return []
        lines = body.splitlines()
        sections: List[_Section] = []
        for idx, heading in enumerate(headings):
            start = heading.body_line_end - 1  # 0-based content start
            if idx + 1 < len(headings):
                end = headings[idx + 1].body_line - 1  # 0-based, exclusive
            else:
                end = len(lines)
            if end <= start:
                continue
            words = " ".join(lines[start:end]).lower().split()
            if len(words) < self._min_words:
                continue
            sections.append(
                _Section(
                    block=cf,
                    heading=heading.text,
                    body_line=heading.body_line,
                    words=words,
                )
            )
        return sections

    def _is_generated(self, cf: ContentBlock) -> bool:
        raw = cf.read_body(strip_code_blocks=False)
        return bool(raw) and _GENERATED_MARKER.search(raw) is not None

    @staticmethod
    def _relative_path(cf: ContentBlock, context: RepositoryContext) -> str:
        try:
            return cf.resolved_path.relative_to(context.root_path.resolve()).as_posix()
        except ValueError:
            return str(cf.path)

    def check(self, context: RepositoryContext) -> List[RuleViolation]:
        candidates = [
            cf
            for cf in gather_all_content_blocks(context)
            if cf.category in _INSTRUCTION_CATEGORIES
        ]
        if self._ignore_generated:
            candidates = [cf for cf in candidates if not self._is_generated(cf)]
        if len(candidates) < self.MIN_FILES:
            return []

        sections: List[_Section] = []
        for cf in candidates:
            sections.extend(self._extract_sections(cf))
        # Deterministic order: violations anchor on the later section of
        # each pair under this ordering.
        sections.sort(key=lambda s: (str(s.block.path), s.body_line))
        # Bound the O(sections^2) comparison: past the cap, later sections
        # (in path order) simply do not participate.  Documented in the
        # rule doc; raise `similarity-max-sections` to scan more.
        if len(sections) > self._max_sections:
            sections = sections[: self._max_sections]

        threshold = self._threshold
        violations: List[RuleViolation] = []
        matcher = SequenceMatcher(autojunk=False)
        for j in range(1, len(sections)):
            anchor = sections[j]
            # SequenceMatcher caches stats for seq2 — keep the anchor there
            # and vary seq1 across the inner loop.
            matcher.set_seq2(anchor.words)
            anchor_len = len(anchor.words)
            for i in range(j):
                other = sections[i]
                if other.block.resolved_path == anchor.block.resolved_path:
                    continue
                other_len = len(other.words)
                # Staged prefilters, cheapest first. The length bound is
                # difflib's real_quick_ratio() formula computed from stored
                # lengths (no set_seq1() needed): ratio() can never exceed
                # 2*min/(min+max), so this skip is results-identical to
                # computing ratio() directly. (A bare min/max < threshold
                # bound would be unsound — it drops genuinely-similar pairs
                # where one copy only gained a sentence.)
                if 2.0 * min(other_len, anchor_len) / (other_len + anchor_len) < threshold:
                    continue
                matcher.set_seq1(other.words)
                if matcher.quick_ratio() < threshold:
                    continue
                if other.words == anchor.words:
                    continue  # identical copies are intentional sync
                ratio = matcher.ratio()
                if not threshold <= ratio < 1.0:
                    continue
                other_path = self._relative_path(other.block, context)
                other_line = other.block.file_line(other.body_line)
                percent = int(ratio * 100)
                violations.append(
                    self.violation(
                        f"Section '{anchor.heading}' is {percent}% similar to "
                        f"'{other.heading}' in {other_path}:{other_line} — "
                        f"likely a drifted copy; reconcile them or make them "
                        f"identical",
                        block=anchor.block,
                        line=anchor.body_line,
                    )
                )
        return violations
