#!/usr/bin/env python3
"""Generate documentation site content from code sources.

Produces:
  - docs/rules/index.md          All rules overview table
  - docs/rules/<group>.md        Per-group rule pages
  - docs/rules/content/<rule>.md Individual content rule pages
  - docs/cli.md                  CLI reference from argparse
  - docs/research.md             Research citations page
  - Injects stats into docs/index.md

Generated files are marked with a header comment and should not be edited by hand.
"""

import json
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from skillsaw.rules.builtin import BUILTIN_RULES  # noqa: E402
from skillsaw.config import LinterConfig  # noqa: E402
from skillsaw import __version__  # noqa: E402

GENERATED_HEADER = (
    "<!-- Generated by scripts/generate-site-content.py — do not edit by hand -->\n\n"
)

_TITLE_OVERRIDES = {
    "mcp": "MCP",
    "apm": "APM",
}


def _format_title(slug):
    """Convert a slug to a display title, respecting acronyms."""
    words = slug.replace("-", " ").split()
    return " ".join(_TITLE_OVERRIDES.get(w, w.capitalize()) for w in words)

# ---------------------------------------------------------------------------
# Rule groups — mirrors scripts/generate-docs.py
# ---------------------------------------------------------------------------

RULE_GROUPS = [
    (
        "agentskills.io",
        "agentskills",
        [
            "agentskill-valid",
            "agentskill-name",
            "agentskill-description",
            "agentskill-structure",
            "agentskill-evals",
            "agentskill-evals-required",
        ],
        "These rules validate skills against the [agentskills.io specification]"
        "(https://agentskills.io/specification). They auto-enable for agentskills "
        "repos, single plugins, and marketplaces whenever skills are detected.",
    ),
    (
        "Plugin Structure",
        "plugin-structure",
        ["plugin-json-required", "plugin-json-valid", "plugin-naming", "plugin-readme"],
        None,
    ),
    (
        "Command Format",
        "command-format",
        ["command-naming", "command-frontmatter", "command-sections", "command-name-format"],
        None,
    ),
    (
        "Marketplace",
        "marketplace",
        ["marketplace-json-valid", "marketplace-registration"],
        None,
    ),
    (
        "Agents",
        "agents",
        ["agent-frontmatter"],
        None,
    ),
    (
        "Hooks",
        "hooks",
        ["hooks-json-valid"],
        None,
    ),
    (
        "MCP (Model Context Protocol)",
        "mcp",
        ["mcp-valid-json", "mcp-prohibited"],
        None,
    ),
    (
        "Rules Directory",
        "rules-directory",
        ["rule-valid"],
        None,
    ),
    (
        "Cursor",
        "cursor",
        ["cursor-rule-valid"],
        "Validates `.cursor/rules/*.mdc` frontmatter fields: `description`, "
        "`globs`, and `alwaysApply`. The set of recognized keys is configurable "
        "via `valid-keys`.",
    ),
    (
        "OpenClaw",
        "openclaw",
        ["openclaw-metadata"],
        "Validates `metadata.openclaw` in SKILL.md frontmatter against the "
        "[openclaw spec](https://docs.openclaw.ai/tools/skills). Only fires "
        "when `metadata.openclaw` is present.",
    ),
    (
        "Instruction Files",
        "instruction-files",
        ["instruction-file-valid", "instruction-imports-valid"],
        "Validates AI coding assistant instruction files (AGENTS.md, CLAUDE.md, "
        "GEMINI.md) at the repository root. Checks encoding, non-emptiness, and "
        "that `@import` references resolve to existing files. Disabled by default.",
    ),
    (
        "Context Budget",
        "context-budget",
        ["context-budget"],
        "Warns when instruction and configuration files exceed recommended "
        "token limits. Uses a `len(text) / 4` approximation for token counting. "
        "Supports per-category `warn` and `error` thresholds. Disabled by default.",
    ),
    (
        "Content Intelligence",
        "content-intelligence",
        [
            "content-weak-language",
            "content-tautological",
            "content-critical-position",
            "content-redundant-with-tooling",
            "content-instruction-budget",
            "content-negative-only",
            "content-section-length",
            "content-contradiction",
            "content-hook-candidate",
            "content-actionability-score",
            "content-cognitive-chunks",
            "content-embedded-secrets",
            "content-banned-references",
            "content-inconsistent-terminology",
            "content-broken-internal-reference",
            "content-unlinked-internal-reference",
            "content-placeholder-text",
        ],
        "Rules that go beyond structural validation to analyze the *quality* of "
        "instruction files. Built on attention research "
        "([lost-in-the-middle](https://arxiv.org/abs/2307.03172), "
        "[instruction-following limits](https://openreview.net/forum?id=R6q67CDBCH)) "
        "and prompt engineering best practices. Most support LLM-powered fixes via "
        "`skillsaw fix --llm`. See the [research page](../research.md) for the full "
        "research basis behind each rule.",
    ),
    (
        "CodeRabbit",
        "coderabbit",
        ["coderabbit-yaml-valid"],
        "Validates `.coderabbit.yaml` config files for YAML syntax. "
        "Instruction text fields (`reviews.instructions`, per-path "
        "instructions, per-tool instructions, `chat.instructions`) are "
        "automatically checked by the content-* rules. Auto-enabled "
        "when `.coderabbit.yaml` is detected.",
    ),
    (
        "Promptfoo Evals",
        "promptfoo",
        ["promptfoo-valid", "promptfoo-assertions", "promptfoo-metadata"],
        "Validates [promptfoo](https://www.promptfoo.dev/) eval YAML configs "
        "found in `evals/` directories of plugins and skills. "
        "`promptfoo-valid` auto-enables when eval files are detected; "
        "`promptfoo-assertions` and `promptfoo-metadata` are opt-in policy rules.",
    ),
    (
        "APM (Agent Package Manager)",
        "apm",
        ["apm-yaml-valid", "apm-structure-valid"],
        "Validates repositories using the [APM](https://github.com/microsoft/apm) "
        "directory layout (`.apm/`). Auto-enables when `.apm/` is detected.",
    ),
]

CONTENT_RULE_IDS = [
    rule_id
    for group_name, _, rule_ids, _ in RULE_GROUPS
    if group_name == "Content Intelligence"
    for rule_id in rule_ids
]

CLAUDE_CODE_SLUGS = {
    "plugin-structure", "command-format", "marketplace",
    "agents", "hooks", "mcp", "rules-directory",
}


# ---------------------------------------------------------------------------
# Data collection
# ---------------------------------------------------------------------------


def collect_rules():
    """Instantiate all rules and merge with config defaults."""
    defaults = LinterConfig.default()
    rules = {}
    for rule_class in BUILTIN_RULES:
        rule = rule_class()
        rule_config = defaults.rules.get(rule.rule_id, {})
        enabled = rule_config.get("enabled", True)

        if enabled == "auto":
            severity_str = f"{rule.default_severity().value} (auto)"
        elif enabled is False:
            severity_str = f"{rule.default_severity().value} (disabled)"
        else:
            severity_str = rule.default_severity().value

        fix_types = []
        if rule.supports_autofix:
            fix_types.append("auto")
        if rule.llm_fix_prompt is not None:
            fix_types.append("llm")

        repo_types_str = ""
        if rule.repo_types:
            repo_types_str = ", ".join(sorted(t.value for t in rule.repo_types))

        rules[rule.rule_id] = {
            "rule_id": rule.rule_id,
            "description": rule.description,
            "severity": severity_str,
            "fix": ", ".join(fix_types) if fix_types else "-",
            "config_schema": rule.config_schema,
            "since": rule.since,
            "repo_types": repo_types_str,
            "llm_fix_prompt": rule.llm_fix_prompt,
            "enabled": enabled,
        }
    return rules


def parse_research():
    """Parse content-rules-research.md into per-rule sections."""
    research_path = ROOT / "docs" / "designs" / "content-rules-research.md"
    if not research_path.exists():
        return {}

    text = research_path.read_text()
    sections = {}
    current_id = None
    current_lines = []

    for line in text.split("\n"):
        m = re.match(r"^## (content-[\w-]+)", line)
        if m:
            if current_id:
                sections[current_id] = "\n".join(current_lines).strip()
            current_id = m.group(1)
            current_lines = []
        elif current_id is not None:
            if line.strip() == "---":
                continue
            current_lines.append(line)

    if current_id:
        sections[current_id] = "\n".join(current_lines).strip()

    # Also grab the cross-cutting and budget sections
    for heading in ["Instruction Budget vs. Context Budget", "Key Papers (Cross-Cutting)"]:
        m = re.search(rf"^## {re.escape(heading)}$", text, re.MULTILINE)
        if m:
            start = m.end()
            next_h2 = re.search(r"^## ", text[start:], re.MULTILINE)
            end = start + next_h2.start() if next_h2 else len(text)
            key = heading.lower().replace(" ", "-").replace("(", "").replace(")", "")
            sections[key] = text[start:end].strip().replace("---", "").strip()

    return sections


def _extract_args(subparser):
    """Extract argument info from an argparse subparser."""
    import argparse as _argparse

    args = []
    for act in subparser._actions:
        if isinstance(act, _argparse._HelpAction):
            continue
        flags = act.option_strings
        if not flags:
            continue
        if act.help == _argparse.SUPPRESS:
            continue

        flag_str = ", ".join(f"`{f}`" for f in flags)
        help_text = act.help or ""
        default = act.default
        if default in (None, False, [], _argparse.SUPPRESS):
            default_str = ""
        elif isinstance(default, Path):
            default_str = ""
        else:
            default_str = str(default)

        choices_str = ""
        if act.choices:
            choices_str = ", ".join(str(c) for c in act.choices)

        args.append({
            "flags": flag_str,
            "help": help_text,
            "default": default_str,
            "choices": choices_str,
        })
    return args


def _extract_subcommands(parser, prefix=""):
    """Extract subcommand info from a parser, recursively for nested subparsers."""
    import argparse as _argparse

    commands = []
    for action in parser._subparsers._actions:
        if not isinstance(action, _argparse._SubParsersAction):
            continue

        help_map = {ca.dest: ca.help for ca in action._choices_actions}

        for name, subparser in action.choices.items():
            full_name = f"{prefix} {name}".strip() if prefix else name
            commands.append({
                "name": full_name,
                "help": help_map.get(name, ""),
                "args": _extract_args(subparser),
            })

            if subparser._subparsers:
                commands.extend(_extract_subcommands(subparser, full_name))

    return commands


def parse_cli():
    """Extract CLI subcommands and arguments by introspecting the real parsers."""
    from skillsaw.__main__ import _build_parser
    from skillsaw.marketplace.cli import _build_add_parser

    parser = _build_parser()
    commands = _extract_subcommands(parser)

    for cmd in commands:
        if cmd["name"] == "add":
            add_parser = _build_add_parser()
            add_subs = _extract_subcommands(add_parser, prefix="add")
            idx = commands.index(cmd)
            commands[idx:idx + 1] = [cmd] + add_subs
            break

    return commands


# ---------------------------------------------------------------------------
# Page generators
# ---------------------------------------------------------------------------


def _rule_table(rule_ids, rules_data, content_link_prefix="content/"):
    """Generate a markdown table for a list of rule IDs."""
    lines = [
        "| Rule ID | Description | Default Severity | Autofix |",
        "|---------|-------------|------------------|---------|",
    ]
    for rule_id in rule_ids:
        r = rules_data[rule_id]
        if rule_id in CONTENT_RULE_IDS:
            short = rule_id.replace("content-", "")
            link = f"[`{rule_id}`]({content_link_prefix}{short}.md)"
        else:
            link = f"`{rule_id}`"
        lines.append(f"| {link} | {r['description']} | {r['severity']} | {r['fix']} |")
    return "\n".join(lines)


def _params_table(rule_id, schema):
    """Generate a config parameters table."""
    lines = [
        f"\n**`{rule_id}` parameters:**\n",
        "| Parameter | Description | Default |",
        "|-----------|-------------|---------|",
    ]
    for param_name, param_info in schema.items():
        desc = param_info["description"]
        default = f"`{json.dumps(param_info['default'])}`"
        lines.append(f"| `{param_name}` | {desc} | {default} |")
    return "\n".join(lines)


def generate_rules_index(rules_data):
    """Generate docs/rules/index.md — overview of all rules."""
    lines = [GENERATED_HEADER, "# Rules Reference\n"]
    lines.append(f"skillsaw includes **{len(rules_data)}** builtin rules ")
    lines.append("organized into the following categories:\n")

    for group_name, slug, rule_ids, description in RULE_GROUPS:
        count = len(rule_ids)
        plural = "rule" if count == 1 else "rules"
        if slug == "content-intelligence":
            lines.append(f"- [{group_name}](content/index.md) ({count} {plural})")
        elif slug in CLAUDE_CODE_SLUGS:
            lines.append(f"- [{group_name}](claude-code/{slug}.md) ({count} {plural})")
        else:
            lines.append(f"- [{group_name}]({slug}.md) ({count} {plural})")

    lines.append("\n## All Rules\n")
    lines.append("| Rule ID | Description | Default Severity | Autofix | Category |")
    lines.append("|---------|-------------|------------------|---------|----------|")

    for group_name, slug, rule_ids, _ in RULE_GROUPS:
        for rule_id in rule_ids:
            r = rules_data[rule_id]
            if rule_id in CONTENT_RULE_IDS:
                link = f"[`{rule_id}`](content/{rule_id.replace('content-', '')}.md)"
            else:
                link = f"`{rule_id}`"
            lines.append(
                f"| {link} | {r['description']} | {r['severity']} | {r['fix']} | {group_name} |"
            )

    return "\n".join(lines) + "\n"


def generate_group_page(group_name, slug, rule_ids, description, rules_data):
    """Generate a per-group rule page."""
    is_content = slug == "content-intelligence"
    lines = [GENERATED_HEADER, f"# {group_name}\n"]

    if description:
        if is_content:
            description = description.replace("../research.md", "../../research.md")
        lines.append(f"{description}\n")

    content_prefix = "" if is_content else "content/"
    lines.append(_rule_table(rule_ids, rules_data, content_link_prefix=content_prefix))
    lines.append("")

    for rule_id in rule_ids:
        r = rules_data[rule_id]
        if r["config_schema"]:
            lines.append(_params_table(rule_id, r["config_schema"]))
            lines.append("")

    return "\n".join(lines) + "\n"


def generate_content_rule_page(rule_id, rules_data, research):
    """Generate an individual content rule page."""
    r = rules_data[rule_id]
    short_name = rule_id.replace("content-", "")
    title = _format_title(short_name)

    lines = [GENERATED_HEADER, f"# {title}\n"]
    lines.append(f"**Rule ID:** `{rule_id}`\n")
    lines.append(f"{r['description']}\n")

    # Metadata badges
    lines.append("| | |")
    lines.append("|---|---|")
    lines.append(f"| **Severity** | {r['severity']} |")
    lines.append(f"| **Autofix** | {r['fix']} |")
    lines.append(f"| **Since** | v{r['since']} |")
    if r["repo_types"]:
        lines.append(f"| **Repo Types** | {r['repo_types']} |")
    lines.append("")

    if r["config_schema"]:
        lines.append("## Configuration\n")
        lines.append("| Parameter | Description | Default |")
        lines.append("|-----------|-------------|---------|")
        for param_name, param_info in r["config_schema"].items():
            desc = param_info["description"]
            default = f"`{json.dumps(param_info['default'])}`"
            lines.append(f"| `{param_name}` | {desc} | {default} |")
        lines.append("")

    research_text = research.get(rule_id, "")
    if research_text:
        lines.append("## Research Basis\n")
        # Rewrite intra-doc anchors to point to the research page
        research_text = research_text.replace(
            "(#instruction-budget-vs-context-budget)",
            "(../../research.md#instruction-budget-vs-context-budget)",
        )
        lines.append(research_text)
        lines.append("")

    return "\n".join(lines) + "\n"


def generate_claude_code_index(rules_data):
    """Generate docs/rules/claude-code/index.md — combined Claude Code rules page."""
    lines = [GENERATED_HEADER, "# Claude Code\n"]
    lines.append(
        "Rules that validate [Claude Code](https://docs.claude.com/en/docs/claude-code) "
        "plugins, commands, marketplaces, agents, hooks, MCP servers, and rules.\n"
    )

    for group_name, slug, rule_ids, description in RULE_GROUPS:
        if slug not in CLAUDE_CODE_SLUGS:
            continue
        lines.append(f"## {group_name}\n")
        if description:
            lines.append(f"{description}\n")
        lines.append(_rule_table(rule_ids, rules_data))
        lines.append("")

        for rule_id in rule_ids:
            r = rules_data[rule_id]
            if r["config_schema"]:
                lines.append(_params_table(rule_id, r["config_schema"]))
                lines.append("")

    return "\n".join(lines) + "\n"


def generate_cli_reference(commands):
    """Generate docs/cli.md from parsed argparse data."""
    lines = [GENERATED_HEADER, "# CLI Reference\n"]
    lines.append("```\nskillsaw [command] [options]\n```\n")

    for cmd in commands:
        depth = cmd["name"].count(" ")
        heading = "#" * (depth + 2)
        lines.append(f"{heading} `skillsaw {cmd['name']}`\n")
        if cmd["help"]:
            lines.append(f"{cmd['help']}\n")

        if cmd["args"]:
            lines.append("| Flag | Description | Default |")
            lines.append("|------|-------------|---------|")
            for arg in cmd["args"]:
                default = f"`{arg['default']}`" if arg["default"] else ""
                desc = arg["help"]
                if arg.get("choices"):
                    desc += f" (choices: {arg['choices']})"
                lines.append(f"| {arg['flags']} | {desc} | {default} |")
            lines.append("")

    return "\n".join(lines) + "\n"


def generate_research_page(research):
    """Generate docs/research.md from the research citations."""
    lines = [GENERATED_HEADER]
    lines.append("# Research & Justification\n")
    lines.append(
        "skillsaw's content intelligence rules analyze the *quality* of AI context "
        "building blocks. Each rule is grounded in published research on LLM behavior, "
        "prompt engineering best practices, or established software engineering principles.\n"
    )

    for rule_id in CONTENT_RULE_IDS:
        if rule_id not in research:
            continue
        short = rule_id.replace("content-", "")
        title = _format_title(short)
        lines.append(f"## [{title}](rules/content/{short}.md)\n")
        lines.append(f"**Rule:** `{rule_id}`\n")
        lines.append(research[rule_id])
        lines.append("\n---\n")

    # Budget comparison section
    budget_key = "instruction-budget-vs.-context-budget"
    if budget_key in research:
        lines.append("## Instruction Budget vs. Context Budget\n")
        lines.append(research[budget_key])
        lines.append("\n---\n")

    # Cross-cutting papers
    papers_key = "key-papers-cross-cutting"
    if papers_key in research:
        lines.append("## Key Papers (Cross-Cutting)\n")
        lines.append(research[papers_key])
        lines.append("")

    return "\n".join(lines) + "\n"


def inject_stats(index_path, rules_data):
    """Replace stat markers in docs/index.md."""
    text = index_path.read_text()
    text = text.replace("<!-- RULE_COUNT -->", str(len(rules_data)))
    index_path.write_text(text)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main():
    docs_dir = ROOT / "docs"
    rules_dir = docs_dir / "rules"
    content_dir = rules_dir / "content"

    rules_dir.mkdir(parents=True, exist_ok=True)
    content_dir.mkdir(parents=True, exist_ok=True)
    claude_code_dir = rules_dir / "claude-code"
    claude_code_dir.mkdir(parents=True, exist_ok=True)

    # Copy logo
    images_dir = docs_dir / "images"
    images_dir.mkdir(parents=True, exist_ok=True)
    logo_src = ROOT / "images" / "logo.png"
    logo_dst = images_dir / "logo.png"
    if logo_src.exists():
        shutil.copy2(logo_src, logo_dst)

    print("Collecting rule data...")
    rules_data = collect_rules()

    print("Parsing research citations...")
    research = parse_research()

    print("Parsing CLI definitions...")
    commands = parse_cli()

    # Rules index
    (rules_dir / "index.md").write_text(generate_rules_index(rules_data))
    print(f"  rules/index.md ({len(rules_data)} rules)")

    # Claude Code index
    (claude_code_dir / "index.md").write_text(generate_claude_code_index(rules_data))
    print("  rules/claude-code/index.md")

    # Group pages
    for group_name, slug, rule_ids, description in RULE_GROUPS:
        content = generate_group_page(group_name, slug, rule_ids, description, rules_data)
        if slug == "content-intelligence":
            (content_dir / "index.md").write_text(content)
            print("  rules/content/index.md")
        elif slug in CLAUDE_CODE_SLUGS:
            (claude_code_dir / f"{slug}.md").write_text(content)
            print(f"  rules/claude-code/{slug}.md")
        else:
            (rules_dir / f"{slug}.md").write_text(content)
            print(f"  rules/{slug}.md")

    # Redirects for old Claude Code rule paths
    for slug in CLAUDE_CODE_SLUGS:
        redirect = (
            f'<meta http-equiv="refresh" content="0; url=../claude-code/{slug}/">\n'
            f"Moved to [claude-code/{slug}](claude-code/{slug}.md)\n"
        )
        (rules_dir / f"{slug}.md").write_text(redirect)

    # Redirect for old skills-agents-hooks path
    redirect = (
        '<meta http-equiv="refresh" content="0; url=../claude-code/">\n'
        "Moved to [Claude Code](claude-code/index.md)\n"
    )
    (rules_dir / "skills-agents-hooks.md").write_text(redirect)

    # Individual content rule pages
    for rule_id in CONTENT_RULE_IDS:
        short = rule_id.replace("content-", "")
        content = generate_content_rule_page(rule_id, rules_data, research)
        (content_dir / f"{short}.md").write_text(content)
        print(f"  rules/content/{short}.md")

    # CLI reference
    (docs_dir / "cli.md").write_text(generate_cli_reference(commands))
    print("  cli.md")

    # Research page
    (docs_dir / "research.md").write_text(generate_research_page(research))
    print("  research.md")

    # Inject stats into index
    inject_stats(docs_dir / "index.md", rules_data)
    print("  index.md (stats injected)")

    print(f"\nDone. Generated site content for skillsaw v{__version__}.")


if __name__ == "__main__":
    main()
