#!/usr/bin/env python3
"""Generate documentation site content from code sources.

Produces:
  - docs/rules/index.md          All rules overview table
  - docs/rules/<group>.md        Per-group rule pages
  - docs/rules/<rule-id>.md      Individual rule pages (stable URL per rule)
  - docs/cli.md                  CLI reference from argparse
  - docs/research.md             Research citations page
  - docs/llms.txt                llms.txt index for agents (llmstxt.org)
  - docs/llms-full.txt           Full docs as one plain-markdown file
  - Injects stats into docs/index.md

Generated files are marked with a header comment and should not be edited by hand.
"""

import json
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from skillsaw.rules.builtin import BUILTIN_RULES  # noqa: E402
from skillsaw.config import LinterConfig  # noqa: E402
from skillsaw.rule_docs import load_rule_docs  # noqa: E402
from skillsaw import __version__  # noqa: E402

GENERATED_HEADER = (
    "<!-- Generated by scripts/generate-site-content.py — do not edit by hand -->\n\n"
)

SITE_URL = "https://skillsaw.org"
RAW_BASE = "https://raw.githubusercontent.com/stbenjam/skillsaw/main"
SITE_SUMMARY = "A configurable linter for agent skills, plugins, and AI coding assistant context"

_TITLE_OVERRIDES = {
    "mcp": "MCP",
    "apm": "APM",
}


def _format_title(slug):
    """Convert a slug to a display title, respecting acronyms."""
    words = slug.replace("-", " ").split()
    return " ".join(_TITLE_OVERRIDES.get(w, w.capitalize()) for w in words)


# ---------------------------------------------------------------------------
# Rule groups — mirrors scripts/generate-docs.py
# ---------------------------------------------------------------------------

RULE_GROUPS = [
    (
        "agentskills.io",
        "agentskills",
        [
            "agentskill-valid",
            "agentskill-name",
            "agentskill-rename-refs",
            "agentskill-description",
            "agentskill-structure",
            "agentskill-evals",
            "agentskill-evals-required",
            "agentskill-unreferenced-files",
        ],
        "These rules validate skills against the [agentskills.io specification]"
        "(https://agentskills.io/specification). They auto-enable wherever skills "
        "are detected — agentskills repos, single plugins, marketplaces, "
        "`.claude/` directories, Codex plugins and marketplaces, and Agent "
        "Plugin packages.",
    ),
    (
        "Vercel",
        "vercel",
        ["skills-lock-valid"],
        "Validates every `skills-lock.json` written by the "
        "[Vercel skills CLI](https://github.com/vercel-labs/skills): strict JSON, "
        "the versioned project-lock shape, required source metadata, digest syntax, "
        "and paths that remain portable across machines. Lockfiles are discovered "
        "recursively for monorepos and the rule auto-enables when one is present.",
    ),
    (
        "Agent Plugins",
        "agent-plugins",
        ["agent-plugin-json-valid", "agent-plugin-mcp-valid", "agent-plugin-required"],
        "Validates portable plugin packages against the "
        "[Agent Plugins v1 specification]"
        "(https://agent-plugins.org/specification). The manifest rule checks "
        "the required root `plugin.json`; the MCP rule checks optional root "
        "`mcp.json`. Auto-enabled when a root or immediate `plugins/*` "
        "manifest declares a canonical Agent Plugins schema; use "
        "`--type agent-plugin` to force validation.",
    ),
    (
        "Claude Code",
        "claude",
        [
            "claude-plugin-json-required",
            "claude-plugin-json-valid",
            "claude-plugin-naming",
            "claude-plugin-readme",
            "claude-command-naming",
            "claude-command-frontmatter",
            "claude-command-sections",
            "claude-command-name-format",
            "claude-agent-frontmatter",
            "claude-marketplace-json-valid",
            "claude-marketplace-registration",
            "claude-settings-dangerous",
            "claude-rules-valid",
        ],
        "Validates the Claude Code formats: plugin manifests "
        "(`.claude-plugin/plugin.json`), `marketplace.json` catalogs, "
        "command and agent frontmatter, `.claude/settings.json` security, "
        "and `.claude/rules/` files. These rules carry the `claude-` prefix "
        "(mirroring `codex-`); their pre-0.18 bare names still work as "
        "legacy aliases everywhere a rule is named.",
    ),
    (
        "OpenAI Codex",
        "codex",
        [
            "codex-openai-metadata",
            "codex-plugin-json-valid",
            "codex-plugin-structure",
            "codex-marketplace-json-valid",
            "codex-marketplace-registration",
        ],
        "Validates OpenAI's optional "
        "[skill metadata](https://learn.chatgpt.com/docs/build-skills#optional-metadata) "
        "in `agents/openai.yaml`, plus Codex plugins and marketplaces against "
        "the [Codex plugin specification]"
        "(https://developers.openai.com/plugins/build/plugins). The metadata "
        "rule auto-enables for Agent Skills; the plugin and marketplace rules "
        "auto-enable only when their Codex manifests are present.",
    ),
    (
        "Hooks",
        "hooks",
        [
            "hooks-json-valid",
            "hooks-dangerous",
            "hooks-prohibited",
        ],
        "Validates hook configuration. The security rules scan hooks in "
        "`hooks.json`, `.cursor/hooks.json`, `.claude/settings*.json`, and "
        "skill/agent frontmatter (`hooks:` key) for supply-chain "
        "attack patterns (inspired by the "
        "[Shai-Hulud attack](https://safedep.io/mini-shai-hulud-strikes-again-314-npm-packages-compromised/)).",
    ),
    (
        "Security",
        "security",
        [
            "security-invisible-unicode",
            "security-hidden-instructions",
            "security-encoded-payload",
            "security-dynamic-context",
        ],
        "Content-validation rules that catch payloads and instructions "
        "invisible to human review: invisible/bidi unicode smuggling (ASCII "
        "smuggling, Trojan Source), agent directives hidden in HTML comments "
        "or Markdown link labels, and long high-entropy base64/hex blobs that "
        "can smuggle encoded payloads, plus unallowlisted dynamic-context "
        "commands in agent content. They complement `hooks-dangerous`, "
        "`claude-settings-dangerous`, and `content-embedded-secrets`, which cover the "
        "executable and credential sides of the same threat.",
    ),
    (
        "MCP (Model Context Protocol)",
        "mcp",
        ["mcp-valid-json", "mcp-prohibited"],
        None,
    ),
    (
        "OpenClaw",
        "openclaw",
        ["openclaw-metadata"],
        "Validates `metadata.openclaw` in SKILL.md frontmatter against the "
        "[OpenClaw spec](https://docs.openclaw.ai/tools/skills). Only fires "
        "when `metadata.openclaw` is present.",
    ),
    (
        "Cursor",
        "cursor",
        ["cursor-rules-valid", "cursor-hooks-valid"],
        "Validates Cursor's repository-shipped configuration under every `.cursor/` "
        "directory in the repository, the root one and any in a monorepo "
        "subpackage: `rules/**/*.mdc` "
        "frontmatter (the fields that decide whether a rule ever activates) and "
        "`.cursor/hooks.json` structure. Cursor reads AGENTS.md for portable "
        "instructions, so no Cursor-specific instruction format is validated. "
        "Enabled automatically wherever a `.cursorrules` file exists, or a "
        "`.cursor/` directory holds Cursor content — `rules/`, `commands/`, "
        "`skills/`, `mcp.json` or `hooks.json`. A `.cursor/` holding only "
        "unrelated files does not activate them.",
    ),
    (
        "Devin",
        "devin",
        ["devin-rules-valid", "devin-skill-valid"],
        "Validates Devin CLI/Desktop workspace rules under `.devin/rules/` "
        "and legacy `.windsurf/rules/`, plus Devin-native skills whose "
        "frontmatter is optional and extends the portable Agent Skills "
        "dialect. Enabled automatically when Devin repository context is present.",
    ),
    (
        "OpenCode",
        "opencode",
        ["opencode-config-valid"],
        "Validates the OpenCode project config — `opencode.json` or "
        "`opencode.jsonc`, at the "
        "repository root or under any `.opencode/` directory — where a "
        "misspelled key is read, ignored and never reported. OpenCode 2.0 "
        "renames much of the schema while still loading the 1.x spelling, so "
        "**both vocabularies are accepted**; what is reported is a file that "
        "declares both spellings of one setting. Comments and trailing commas "
        "are fine — OpenCode reads `.json` through a JSONC parser. OpenCode "
        "reads AGENTS.md for portable instructions, so no OpenCode-specific "
        "instruction format is validated, and its commands, agents and skills "
        "get the shared content rules. Enabled automatically wherever an "
        "`opencode.json` or `opencode.jsonc` exists, or a `.opencode/` "
        "directory holds OpenCode "
        "content.",
    ),
    (
        "Instruction Files",
        "instruction-files",
        [
            "instruction-file-valid",
            "instruction-imports-valid",
            "claude-md-agents-import",
        ],
        "Validates AI coding assistant instruction files (AGENTS.md, CLAUDE.md, "
        "GEMINI.md, QWEN.md, and Devin-compatible alternatives). Checks encoding, "
        "non-emptiness, and that supported `@import` references resolve to existing "
        "files. Enabled automatically when one of those files is present.",
    ),
    (
        "Context Budget",
        "context-budget",
        ["context-budget"],
        "Warns when instruction and configuration files exceed recommended "
        "token limits. Uses a `len(text) / 4` approximation for token counting. "
        "Supports per-category `warn` and `error` thresholds. Disabled by default.",
    ),
    (
        "Content Intelligence",
        "content-intelligence",
        [
            "content-weak-language",
            "content-tautological",
            "content-description-routing",
            "content-redundant-with-tooling",
            "content-instruction-budget",
            "content-negative-only",
            "content-section-length",
            "content-contradiction",
            "content-hook-candidate",
            "content-cognitive-chunks",
            "content-embedded-secrets",
            "content-banned-references",
            "content-inconsistent-terminology",
            "content-instruction-drift",
            "content-broken-internal-reference",
            "content-broken-external-reference",
            "content-unlinked-internal-reference",
            "content-placeholder-text",
            "content-unclosed-fence",
            "content-repeated-directive",
            "content-emphasis-density",
            "content-missing-stop-condition",
            "content-inline-tool-examples",
            "content-progressive-disclosure",
            "content-mcp-tool-name",
        ],
        "Rules that go beyond structural validation to analyze the *quality* of "
        "instruction files. Built on attention research "
        "([lost-in-the-middle](https://arxiv.org/abs/2307.03172), "
        "[instruction-following limits](https://openreview.net/forum?id=R6q67CDBCH)) "
        "and prompt engineering best practices. See the [research page](../research.md) "
        "for the full research basis behind each rule.",
    ),
    (
        "CodeRabbit",
        "coderabbit",
        ["coderabbit-yaml-valid", "coderabbit-schema-valid"],
        "Validates `.coderabbit.yaml` config files for YAML syntax and, via "
        "`coderabbit-schema-valid`, near-miss unknown top-level keys and the "
        "`reviews.profile` enum against the CodeRabbit schema. "
        "Instruction text fields (`reviews.instructions`, per-path "
        "instructions, per-tool instructions, `chat.instructions`) are "
        "automatically checked by the content-* rules. Auto-enabled "
        "when `.coderabbit.yaml` is detected.",
    ),
    (
        "Promptfoo Evals",
        "promptfoo",
        ["promptfoo-valid", "promptfoo-assertions", "promptfoo-metadata"],
        "Validates [promptfoo](https://www.promptfoo.dev/) eval YAML configs "
        "found in `evals/` directories of plugins and skills. "
        "`promptfoo-valid` auto-enables when eval files are detected; "
        "`promptfoo-assertions` and `promptfoo-metadata` are opt-in policy rules.",
    ),
    (
        "APM (Agent Package Manager)",
        "apm",
        ["apm-yaml-valid", "apm-structure-valid"],
        "Validates repositories using the [APM](https://github.com/microsoft/apm) "
        "directory layout (`.apm/`). Auto-enables when `.apm/` is detected.",
    ),
    (
        "Deprecated",
        "deprecated",
        [
            "content-critical-position",
            "content-actionability-score",
            "skill-frontmatter",
        ],
        "These rules are deprecated and will be removed in a future release. "
        "They no longer run under `enabled: auto`; set `enabled: true` in "
        "`.skillsaw.yaml` to keep running one during the transition. The "
        "content rules encoded attention-era heuristics that newer models no "
        "longer need; `skill-frontmatter` is replaced by "
        "[`agentskill-valid`](agentskill-valid.md).",
    ),
]

CONTENT_RULE_IDS = [
    rule_id
    for group_name, _, rule_ids, _ in RULE_GROUPS
    if group_name == "Content Intelligence"
    for rule_id in rule_ids
]


# ---------------------------------------------------------------------------
# Data collection
# ---------------------------------------------------------------------------


def collect_rules():
    """Instantiate all rules and merge with config defaults."""
    defaults = LinterConfig.default()
    rules = {}
    for rule_class in BUILTIN_RULES:
        rule = rule_class()
        rule_config = defaults.rules.get(rule.rule_id, {})
        enabled = rule_config.get("enabled", True)
        default_severity = rule_config.get("severity") or rule.default_severity().value

        if rule.deprecated is not None:
            severity_str = f"{default_severity} (deprecated)"
        elif enabled == "auto":
            severity_str = f"{default_severity} (auto)"
        elif enabled is False:
            severity_str = f"{default_severity} (disabled)"
        else:
            severity_str = default_severity

        fix_types = []
        if rule.supports_autofix:
            fix_types.append("auto")

        repo_types_str = ""
        if rule.repo_types:
            repo_types_str = ", ".join(sorted(t.value for t in rule.repo_types))

        rules[rule.rule_id] = {
            "rule_id": rule.rule_id,
            "description": rule.description,
            "severity": severity_str,
            "default_severity": default_severity,
            "fix": ", ".join(fix_types) if fix_types else "-",
            "config_schema": rule.config_schema,
            "since": rule.since,
            "repo_types": repo_types_str,
            "enabled": enabled,
            "deprecated": rule.deprecated,
            "deprecated_reason": rule.deprecated_reason,
            "replaced_by": rule.replaced_by,
            "aliases": rule.aliases,
        }
    return rules


def parse_research():
    """Parse content-rules-research.md into per-rule sections."""
    research_path = ROOT / "docs" / "designs" / "content-rules-research.md"
    if not research_path.exists():
        return {}

    text = research_path.read_text()
    sections = {}
    current_id = None
    current_lines = []

    for line in text.split("\n"):
        m = re.match(r"^## (content-[\w-]+)", line)
        if m:
            if current_id:
                sections[current_id] = "\n".join(current_lines).strip()
            current_id = m.group(1)
            current_lines = []
        elif current_id is not None:
            if line.strip() == "---":
                continue
            current_lines.append(line)

    if current_id:
        sections[current_id] = "\n".join(current_lines).strip()

    # Also grab the cross-cutting and budget sections
    for heading in ["Instruction Budget vs. Context Budget", "Key Papers (Cross-Cutting)"]:
        m = re.search(rf"^## {re.escape(heading)}$", text, re.MULTILINE)
        if m:
            start = m.end()
            next_h2 = re.search(r"^## ", text[start:], re.MULTILINE)
            end = start + next_h2.start() if next_h2 else len(text)
            key = heading.lower().replace(" ", "-").replace("(", "").replace(")", "")
            sections[key] = text[start:end].strip().replace("---", "").strip()

    return sections


def _extract_args(subparser):
    """Extract argument info from an argparse subparser."""
    import argparse as _argparse

    args = []
    for act in subparser._actions:
        if isinstance(act, _argparse._HelpAction):
            continue
        flags = act.option_strings
        if not flags:
            continue
        if act.help == _argparse.SUPPRESS:
            continue

        flag_str = ", ".join(f"`{f}`" for f in flags)
        help_text = act.help or ""
        default = act.default
        if default in (None, False, [], _argparse.SUPPRESS):
            default_str = ""
        elif isinstance(default, Path):
            default_str = ""
        else:
            default_str = str(default)

        choices_str = ""
        if act.choices:
            choices_str = ", ".join(str(c) for c in act.choices)

        args.append(
            {
                "flags": flag_str,
                "help": help_text,
                "default": default_str,
                "choices": choices_str,
            }
        )
    return args


def _extract_subcommands(parser, prefix=""):
    """Extract subcommand info from a parser, recursively for nested subparsers."""
    import argparse as _argparse

    commands = []
    for action in parser._subparsers._actions:
        if not isinstance(action, _argparse._SubParsersAction):
            continue

        help_map = {ca.dest: ca.help for ca in action._choices_actions}

        for name, subparser in action.choices.items():
            full_name = f"{prefix} {name}".strip() if prefix else name
            commands.append(
                {
                    "name": full_name,
                    "help": help_map.get(name, ""),
                    "args": _extract_args(subparser),
                }
            )

            if subparser._subparsers:
                commands.extend(_extract_subcommands(subparser, full_name))

    return commands


def parse_cli():
    """Extract CLI subcommands and arguments by introspecting the real parsers."""
    from skillsaw.cli._parser import _build_parser
    from skillsaw.marketplace.cli import _build_add_parser

    parser = _build_parser()
    commands = _extract_subcommands(parser)

    for cmd in commands:
        if cmd["name"] == "add":
            add_parser = _build_add_parser()
            add_subs = _extract_subcommands(add_parser, prefix="add")
            idx = commands.index(cmd)
            commands[idx : idx + 1] = [cmd] + add_subs
            break

    return commands


# ---------------------------------------------------------------------------
# Page generators
# ---------------------------------------------------------------------------


def _table_cell(text):
    """Escape characters that would break a markdown table cell."""
    return str(text).replace("|", "\\|")


def _rule_table(rule_ids, rules_data):
    """Generate a markdown table for a list of rule IDs."""
    lines = [
        "| Rule ID | Description | Default Severity | Autofix |",
        "|---------|-------------|------------------|---------|",
    ]
    for rule_id in rule_ids:
        r = rules_data[rule_id]
        link = f"[`{rule_id}`]({rule_id}.md)"
        lines.append(f"| {link} | {_table_cell(r['description'])} | {r['severity']} | {r['fix']} |")
    return "\n".join(lines)


def _params_table(rule_id, schema):
    """Generate a config parameters table."""
    lines = [
        f"\n**`{rule_id}` parameters:**\n",
        "| Parameter | Description | Default |",
        "|-----------|-------------|---------|",
    ]
    for param_name, param_info in schema.items():
        desc = _table_cell(param_info["description"])
        default = f"`{json.dumps(param_info['default'])}`"
        lines.append(f"| `{param_name}` | {desc} | {default} |")
    return "\n".join(lines)


def generate_rules_index(rules_data):
    """Generate docs/rules/index.md — overview of all rules."""
    lines = [GENERATED_HEADER, "# Rules Reference\n"]
    lines.append(
        f"skillsaw includes **{len(rules_data)}** built-in rules "
        "organized into the following categories:\n"
    )

    for group_name, slug, rule_ids, description in RULE_GROUPS:
        count = len(rule_ids)
        plural = "rule" if count == 1 else "rules"
        lines.append(f"- [{group_name}]({slug}.md) ({count} {plural})")

    lines.append("\n## All Rules\n")
    lines.append("| Rule ID | Description | Default Severity | Autofix | Category |")
    lines.append("|---------|-------------|------------------|---------|----------|")

    for group_name, slug, rule_ids, _ in RULE_GROUPS:
        for rule_id in rule_ids:
            r = rules_data[rule_id]
            link = f"[`{rule_id}`]({rule_id}.md)"
            lines.append(
                f"| {link} | {_table_cell(r['description'])} | {r['severity']}"
                f" | {r['fix']} | {group_name} |"
            )

    return "\n".join(lines) + "\n"


def generate_group_page(group_name, slug, rule_ids, description, rules_data):
    """Generate a per-group rule page."""
    lines = [GENERATED_HEADER, f"# {group_name}\n"]

    if description:
        lines.append(f"{description}\n")

    lines.append(_rule_table(rule_ids, rules_data))
    lines.append("")

    # The Deprecated page explains why each rule was retired.
    reasons = [
        (rule_id, rules_data[rule_id]["deprecated_reason"])
        for rule_id in rule_ids
        if rules_data[rule_id]["deprecated"] and rules_data[rule_id]["deprecated_reason"]
    ]
    if reasons:
        lines.append("## Why these rules were deprecated\n")
        for rule_id, reason in reasons:
            lines.append(f"### [`{rule_id}`]({rule_id}.md)\n")
            lines.append(f"{reason}\n")

    return "\n".join(lines) + "\n"


def generate_rule_page(rule_id, group_name, slug, rules_data, research):
    """Generate an individual rule page at docs/rules/<rule-id>.md.

    This is the rule's stable documentation URL — linked from violation
    output, SARIF helpUri, and `skillsaw explain`.
    """
    r = rules_data[rule_id]

    lines = [GENERATED_HEADER, f"# {rule_id}\n"]

    if r["deprecated"]:
        notice = (
            f'!!! warning "Deprecated"\n'
            f"    Deprecated since v{r['deprecated']} and will be removed in a "
            f"future release. This rule no longer runs under `enabled: auto`; "
            f"set `enabled: true` explicitly to keep it during the transition."
        )
        if r["deprecated_reason"]:
            notice += f"\n\n    {r['deprecated_reason']}"
        if r["replaced_by"]:
            notice += f"\n\n    Use [`{r['replaced_by']}`]({r['replaced_by']}.md) instead."
        lines.append(notice)
        lines.append("")

    lines.append(f"{r['description']}\n")

    if r["aliases"]:
        former = ", ".join(f"`{a}`" for a in r["aliases"])
        lines.append(
            f"*Formerly known as {former}. The legacy name still works in "
            "configs, `--rule`/`--skip-rule`, suppression comments, and "
            "baselines.*\n"
        )

    # Metadata badges
    lines.append("| | |")
    lines.append("|---|---|")
    lines.append(f"| **Severity** | {r['severity']} |")
    lines.append(f"| **Autofix** | {r['fix']} |")
    lines.append(f"| **Since** | v{r['since']} |")
    if r["repo_types"]:
        lines.append(f"| **Repo Types** | {r['repo_types']} |")
    lines.append(f"| **Category** | [{group_name}]({slug}.md) |")
    lines.append("")

    long_docs = load_rule_docs(rule_id)
    if long_docs:
        lines.append(long_docs)
        lines.append("")

    lines.append("## Configuration\n")
    lines.append("```yaml")
    lines.append("rules:")
    lines.append(f"  {rule_id}:")
    lines.append(f"    enabled: {LinterConfig._yaml_value(r['enabled'])}  # true | false | auto")
    lines.append(f"    severity: {r['default_severity']}")
    lines.append("```")
    lines.append("")

    if r["config_schema"]:
        lines.append("| Parameter | Description | Default |")
        lines.append("|-----------|-------------|---------|")
        for param_name, param_info in r["config_schema"].items():
            desc = _table_cell(param_info["description"])
            default = f"`{json.dumps(param_info['default'])}`"
            lines.append(f"| `{param_name}` | {desc} | {default} |")
        lines.append("")

    research_text = research.get(rule_id, "")
    if research_text:
        lines.append("## Research Basis\n")
        # Rewrite intra-doc anchors to point to the research page
        research_text = research_text.replace(
            "(#instruction-budget-vs-context-budget)",
            "(../research.md#instruction-budget-vs-context-budget)",
        )
        lines.append(research_text)
        lines.append("")

    lines.append(
        f"\n*Run `skillsaw explain {rule_id}` to see this documentation "
        "and the rule's effective configuration in your terminal.*"
    )

    return "\n".join(lines) + "\n"


CLI_PATH_SECTION = """\
### Path arguments

`lint` and `fix` accept files as well as directories. A file resolves
to the directory that owns it — never further out, so `lint` reads and
`fix` writes only under the path you named. Manifest rules discover
from a plugin's root, so to run them name the plugin's root directory
rather than a manifest file inside it. Duplicate paths and paths
nested inside another named path are dropped.
"""

CLI_COLOR_SECTION = """\
## Color and hyperlinks

Commands that produce terminal output (`lint`, `fix`, `explain`, `badge`)
decide whether to emit ANSI colors with the standard cascade, strongest
first:

1. `--color` / `--no-color`
2. `FORCE_COLOR` — a non-empty value forces color on even through a pipe
   (`0` forces it off); useful in CI logs that render ANSI
3. `NO_COLOR` — present (even empty) disables color
4. Otherwise color is used only when stdout is a terminal

Piped or redirected output is plain text by default. When color is
enabled on a real terminal (`TERM` other than `dumb`), text output also
emits [OSC 8
hyperlinks](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda):
rule ids link to their documentation pages, file paths become clickable
`file://` links, and the per-rule "Rule docs" URL footer collapses to a
one-line hint. Hyperlinks are never emitted through a pipe, even when
color is forced.
"""


def generate_cli_reference(commands):
    """Generate docs/cli.md from parsed argparse data."""
    lines = [GENERATED_HEADER, "# CLI Reference\n"]
    lines.append("```\nskillsaw [command] [options]\n```\n")

    for cmd in commands:
        depth = cmd["name"].count(" ")
        heading = "#" * (depth + 2)
        lines.append(f"{heading} `skillsaw {cmd['name']}`\n")
        if cmd["help"]:
            lines.append(f"{cmd['help']}\n")

        if cmd["args"]:
            lines.append("| Flag | Description | Default |")
            lines.append("|------|-------------|---------|")
            for arg in cmd["args"]:
                default = f"`{arg['default']}`" if arg["default"] else ""
                desc = arg["help"]
                if arg.get("choices"):
                    desc += f" (choices: {arg['choices']})"
                lines.append(f"| {arg['flags']} | {desc} | {default} |")
            lines.append("")

        if cmd["name"] == "lint":
            lines.append(CLI_PATH_SECTION)

    lines.append(CLI_COLOR_SECTION)
    return "\n".join(lines) + "\n"


def generate_research_page(research):
    """Generate docs/research.md from the research citations."""
    lines = [GENERATED_HEADER]
    lines.append("# Research & Justification\n")
    lines.append(
        "skillsaw's content intelligence rules analyze the *quality* of AI context "
        "building blocks. Each rule is grounded in published research on LLM behavior, "
        "prompt engineering best practices, or established software engineering principles.\n"
    )

    for rule_id in CONTENT_RULE_IDS:
        if rule_id not in research:
            continue
        short = rule_id.replace("content-", "")
        title = _format_title(short)
        lines.append(f"## [{title}](rules/{rule_id}.md)\n")
        lines.append(f"**Rule:** `{rule_id}`\n")
        lines.append(research[rule_id])
        lines.append("\n---\n")

    # Budget comparison section
    budget_key = "instruction-budget-vs.-context-budget"
    if budget_key in research:
        lines.append("## Instruction Budget vs. Context Budget\n")
        lines.append(research[budget_key])
        lines.append("\n---\n")

    # Cross-cutting papers
    papers_key = "key-papers-cross-cutting"
    if papers_key in research:
        lines.append("## Key Papers (Cross-Cutting)\n")
        lines.append(research[papers_key])
        lines.append("")

    return "\n".join(lines) + "\n"


def inject_stats(index_path, rules_data):
    """Replace stat markers in docs/index.md."""
    text = index_path.read_text()
    text = text.replace("<!-- RULE_COUNT -->", str(len(rules_data)))
    index_path.write_text(text)


# ---------------------------------------------------------------------------
# llms.txt / llms-full.txt — plain-text docs endpoints for agents
# ---------------------------------------------------------------------------

# Top-level docs pages in mkdocs.yml nav order, with one-line descriptions for
# the llms.txt index. Mirrors the nav the same way RULE_GROUPS mirrors
# generate-docs.py; guides_coverage_errors() fails the build when this list
# and the on-disk docs/*.md pages drift apart. (mkdocs.yml itself is not
# parseable with yaml.safe_load — it uses !!python/name: tags.)
GUIDES = [
    ("Home", "index.md", "project homepage (HTML-heavy hero page)"),
    ("Getting Started", "getting-started.md", "install skillsaw and run your first lint"),
    ("Autofixing", "autofixing.md", "how deterministic autofixes work and when they apply"),
    (
        "Porting to Agent Plugins",
        "porting.md",
        "convert Claude Code and Codex plugins to Agent Plugins v1",
    ),
    ("Baseline", "baseline.md", "adopt skillsaw gradually by baselining existing violations"),
    (
        "Configuration",
        "configuration.md",
        "the .skillsaw.yaml file: rules, severities, exclusions, suppression",
    ),
    ("Repository Types", "repo-types.md", "how skillsaw detects what it is linting"),
    ("CI Integration", "ci.md", "GitHub Actions, GitLab CI, and PR review comments"),
    ("Pre-commit", "pre-commit.md", "run skillsaw as a pre-commit hook"),
    ("CLI Reference", "cli.md", "every command and flag"),
    ("Custom Rules", "custom-rules.md", "write project-local rules in Python"),
    ("Rule Plugins", "plugins.md", "install and publish pip-distributed rule packages"),
    ("Scaffolding", "scaffolding.md", "generate plugins, skills, commands, agents, and hooks"),
    ("Lint Tree", "lint-tree.md", "the typed node tree rules use for discovery"),
    (
        "Supply Chain Protection",
        "supply-chain-protection.md",
        "the security model and dangerous-configuration rules",
    ),
    ("Research", "research.md", "the research basis behind the content intelligence rules"),
]

# Top-level docs pages deliberately absent from GUIDES (none today).
NON_GUIDE_DOCS = set()


def guides_coverage_errors(docs_dir):
    """Check that GUIDES covers exactly the on-disk top-level docs pages.

    Returns a list of error strings; empty when GUIDES and docs/*.md agree.
    """
    errors = []
    guide_paths = {relpath for _, relpath, _ in GUIDES}
    on_disk = {p.name for p in docs_dir.glob("*.md")}
    for name in sorted(on_disk - guide_paths - NON_GUIDE_DOCS):
        errors.append(
            f"docs/{name} is not listed in GUIDES — add it to GUIDES or "
            "NON_GUIDE_DOCS in scripts/generate-site-content.py"
        )
    for relpath in sorted(guide_paths - on_disk):
        errors.append(f"GUIDES entry docs/{relpath} does not exist on disk")
    return errors


_FENCE_RE = re.compile(r"^ {0,3}(`{3,}|~{3,})")
_TAB_MARKER_RE = re.compile(r'^=== "(.+)"\s*$')
_ADMONITION_RE = re.compile(r'^(?:!!!|\?\?\?)\+? +([\w-]+)(?: +"(.*)")?\s*$')
_ATTR_LIST_RE = re.compile(r"\{:? *\.[\w][\w .-]*\}")
_ICON_RE = re.compile(r":([a-z][a-z0-9_+-]*):")


_NUMERIC_ICON_RE = re.compile(r":material-numeric-(\d+)-circle:")


_BACKTICK_RUN_RE = re.compile(r"`+")


def _split_code_spans(line):
    """Split a line into (is_span, text) segments, CommonMark span rules.

    A code span opens with a run of N backticks and closes at the next run
    of exactly N backticks, so ``literal ` inside`` is one span. An
    unmatched run is plain text.
    """
    segments = []
    pos = 0
    while pos < len(line):
        opener = _BACKTICK_RUN_RE.search(line, pos)
        if opener is None:
            segments.append((False, line[pos:]))
            break
        if opener.start() > pos:
            segments.append((False, line[pos : opener.start()]))
        length = opener.end() - opener.start()
        closer = None
        for run in _BACKTICK_RUN_RE.finditer(line, opener.end()):
            if run.end() - run.start() == length:
                closer = run
                break
        if closer is None:
            segments.append((False, line[opener.start() : opener.end()]))
            pos = opener.end()
        else:
            segments.append((True, line[opener.start() : closer.end()]))
            pos = closer.end()
    return segments


def _strip_inline_noise(line):
    """Remove mkdocs-material attr lists and icon shortcodes from a prose line.

    Inline code spans are preserved verbatim — documentation may legitimately
    show a literal `:sparkles:` or `{ .class }` inside backticks, including
    multi-backtick spans quoting backtick-containing content.
    """

    def _strip(segment):
        original = segment
        segment = _NUMERIC_ICON_RE.sub(r"\1.", segment)
        segment = _ATTR_LIST_RE.sub("", segment)
        segment = _ICON_RE.sub("", segment)
        if segment != original:
            # Collapse doubled spaces left where an icon was removed mid-text.
            segment = re.sub(r"(?<=\S) {2,}(?=\S)", " ", segment)
        return segment

    return "".join(text if is_span else _strip(text) for is_span, text in _split_code_spans(line))


def _plain_markdown(text):
    """Convert a docs page to plain markdown for llms-full.txt.

    Drops the generated-file header, flattens mkdocs-material tab and
    admonition blocks (dedenting their bodies by 4), and strips icon
    shortcodes and attr lists from prose. Content inside code fences is
    preserved verbatim, including fences that a tab body indents.
    """
    out = []
    fence = None  # (char, length) of the open fence, or None
    in_block = False  # inside a tab/admonition body
    for line in text.split("\n"):
        if in_block:
            if line.startswith("    "):
                line = line[4:]
            elif line.strip():
                # A non-blank line without the body indent ends the block;
                # blank lines inside the body do not.
                in_block = False
        fence_match = _FENCE_RE.match(line)
        if fence_match:
            delim = fence_match.group(1)
            bare = not line[fence_match.end() :].strip()
            if fence is None:
                fence = (delim[0], len(delim))
            elif delim[0] == fence[0] and len(delim) >= fence[1] and bare:
                # Only a bare delimiter closes a fence (CommonMark): a line
                # like ```bash inside an open fence is content, not a close.
                fence = None
            out.append(line)
            continue
        if fence is not None:
            out.append(line)
            continue
        if line.strip() == GENERATED_HEADER.strip():
            continue
        tab = _TAB_MARKER_RE.match(line)
        if tab:
            out.append(f"**{tab.group(1)}:**")
            in_block = True
            continue
        admonition = _ADMONITION_RE.match(line)
        if admonition:
            kind = admonition.group(1).capitalize()
            title = admonition.group(2)
            out.append(f"**{kind}: {title}**" if title else f"**{kind}**")
            in_block = True
            continue
        if line.startswith("    "):
            # Indented code block (no preceding tab/admonition marker).
            out.append(line)
            continue
        if line.strip() == "---" and (not out or not out[-1].strip()):
            # In-page horizontal rule (preceded by a blank line, so not a
            # setext heading): rewrite to the equivalent `***` so `---`
            # stays reserved for the page joins in llms-full.txt.
            out.append("***")
            continue
        out.append(_strip_inline_noise(line))
    return "\n".join(out)


_MD_LINK_RE = re.compile(r"\[([^\]]+)\]\([^)]*\)")


def _first_sentence_plain(text):
    """First sentence of a RULE_GROUPS description, markdown links flattened."""
    if not text:
        return ""
    flat = _MD_LINK_RE.sub(r"\1", " ".join(text.split()))
    end = flat.find(". ")
    return flat[: end + 1] if end != -1 else flat


def generate_llms_txt(rules_data):
    """Generate docs/llms.txt — a curated markdown index per llmstxt.org.

    Links point at raw.githubusercontent.com because the mkdocs site serves
    only HTML; every linked source is committed.
    """
    lines = [
        "# skillsaw",
        "",
        f"> {SITE_SUMMARY}.",
        "",
        "skillsaw lints the files that steer AI coding agents: skills, plugins,",
        "CLAUDE.md/AGENTS.md instruction files, hooks, and agent configuration.",
        "Run it with `uvx skillsaw` (or `pip install skillsaw`); configure it",
        "with a `.skillsaw.yaml` at the repository root. The complete",
        f"documentation is also served as one file: {SITE_URL}/llms-full.txt.",
        "",
        "## Docs",
        "",
    ]
    for title, relpath, blurb in GUIDES:
        lines.append(f"- [{title}]({RAW_BASE}/docs/{relpath}): {blurb}")

    lines += ["", "## Rules", ""]
    listed = {"rules/index.md"}
    lines.append(
        f"- [Rules Reference]({RAW_BASE}/docs/rules/index.md): overview table of "
        f"all {len(rules_data)} built-in rules"
    )
    for group_name, slug, rule_ids, description in RULE_GROUPS:
        count = len(rule_ids)
        plural = "rule" if count == 1 else "rules"
        blurb = f"{count} {plural}"
        summary = _first_sentence_plain(description)
        if summary:
            blurb = f"{blurb} — {summary}"
        lines.append(f"- [{group_name}]({RAW_BASE}/docs/rules/{slug}.md): {blurb}")
        listed.add(f"rules/{slug}.md")

    lines += ["", "## Optional", ""]
    for _, _, rule_ids, _ in RULE_GROUPS:
        for rule_id in rule_ids:
            path = f"rules/{rule_id}.md"
            if path in listed:
                # The context-budget group page is shadowed by its
                # same-named rule page — list that URL only once.
                continue
            listed.add(path)
            note = ""
            if rules_data[rule_id]["deprecated"]:
                note = f" (deprecated since v{rules_data[rule_id]['deprecated']})"
            lines.append(
                f"- [{rule_id}]({RAW_BASE}/docs/{path}): "
                f"{rules_data[rule_id]['description']}{note}"
            )
    return "\n".join(lines) + "\n"


def generate_llms_full(docs_dir):
    """Generate docs/llms-full.txt — the full docs as one plain-markdown file.

    Concatenates the guides and rule pages in nav order, each passed through
    _plain_markdown(). Excludes docs/index.md (a marketing hero page of raw
    HTML), docs/designs/ (internal, also excluded from the site), and the
    alias/retired-group redirect stubs.
    """
    paths = []
    seen = set()

    def add(relpath):
        if relpath not in seen:
            seen.add(relpath)
            paths.append(relpath)

    for _, relpath, _ in GUIDES:
        if relpath != "index.md":
            add(relpath)
    add("rules/index.md")
    for _, slug, rule_ids, _ in RULE_GROUPS:
        add(f"rules/{slug}.md")
        for rule_id in rule_ids:
            add(f"rules/{rule_id}.md")

    header = "\n".join(
        [
            "# skillsaw — full documentation",
            "",
            f"> {SITE_SUMMARY}.",
            "",
            f"Generated from the skillsaw v{__version__} docs — {SITE_URL}",
        ]
    )
    parts = [header]
    for relpath in paths:
        page = docs_dir / relpath
        if not page.exists():
            raise FileNotFoundError(
                f"docs/{relpath} is missing — run the page generators before "
                "generate_llms_full()"
            )
        parts.append(_plain_markdown(page.read_text(encoding="utf-8")).strip())
    return "\n\n---\n\n".join(parts) + "\n"


def write_llms_outputs(docs_dir, rules_data):
    """Write docs/llms.txt and docs/llms-full.txt from the pages on disk."""
    llms_txt = generate_llms_txt(rules_data)
    (docs_dir / "llms.txt").write_text(llms_txt, encoding="utf-8")
    print(f"  llms.txt ({len(llms_txt.encode('utf-8'))} bytes)")

    llms_full = generate_llms_full(docs_dir)
    (docs_dir / "llms-full.txt").write_text(llms_full, encoding="utf-8")
    print(f"  llms-full.txt ({len(llms_full.encode('utf-8'))} bytes)")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main():
    docs_dir = ROOT / "docs"
    rules_dir = docs_dir / "rules"

    rules_dir.mkdir(parents=True, exist_ok=True)

    # Per-rule pages used to live under docs/rules/content/ — clean up
    # stale checkouts so old and new pages don't coexist.
    legacy_content_dir = rules_dir / "content"
    if legacy_content_dir.exists():
        shutil.rmtree(legacy_content_dir)

    # Copy logo
    images_dir = docs_dir / "images"
    images_dir.mkdir(parents=True, exist_ok=True)
    logo_src = ROOT / "images" / "logo.png"
    logo_dst = images_dir / "logo.png"
    if logo_src.exists():
        shutil.copy2(logo_src, logo_dst)

    print("Collecting rule data...")
    rules_data = collect_rules()

    # Every builtin rule must belong to exactly one group so it gets a
    # documentation page — fail loudly when a new rule is missing.
    grouped_ids = [rule_id for _, _, rule_ids, _ in RULE_GROUPS for rule_id in rule_ids]
    missing = sorted(set(rules_data) - set(grouped_ids))
    duplicated = sorted({rid for rid in grouped_ids if grouped_ids.count(rid) > 1})
    unknown = sorted(set(grouped_ids) - set(rules_data))
    if missing or duplicated or unknown:
        if missing:
            print(f"ERROR: rules missing from RULE_GROUPS: {', '.join(missing)}", file=sys.stderr)
        if duplicated:
            print(
                f"ERROR: rules listed twice in RULE_GROUPS: {', '.join(duplicated)}",
                file=sys.stderr,
            )
        if unknown:
            print(f"ERROR: unknown rules in RULE_GROUPS: {', '.join(unknown)}", file=sys.stderr)
        sys.exit(1)

    print("Parsing research citations...")
    research = parse_research()

    print("Parsing CLI definitions...")
    commands = parse_cli()

    # Rules index
    (rules_dir / "index.md").write_text(generate_rules_index(rules_data))
    print(f"  rules/index.md ({len(rules_data)} rules)")

    # Group pages and individual rule pages
    for group_name, slug, rule_ids, description in RULE_GROUPS:
        content = generate_group_page(group_name, slug, rule_ids, description, rules_data)
        (rules_dir / f"{slug}.md").write_text(content)
        print(f"  rules/{slug}.md")

        for rule_id in rule_ids:
            page = generate_rule_page(rule_id, group_name, slug, rules_data, research)
            (rules_dir / f"{rule_id}.md").write_text(page)
            print(f"  rules/{rule_id}.md")

            # Renamed rules keep their old documentation URLs working via a
            # stub page at the legacy path pointing at the canonical page.
            for alias in rules_data[rule_id]["aliases"]:
                stub = (
                    f"{GENERATED_HEADER}# {alias}\n\n"
                    f"This rule is now [`{rule_id}`]({rule_id}.md) — "
                    f"`{alias}` is a legacy alias that still works in configs, "
                    "`--rule`/`--skip-rule`, suppression comments, and baselines.\n"
                )
                (rules_dir / f"{alias}.md").write_text(stub)
                print(f"  rules/{alias}.md (alias stub)")

    # Group pages retired by the 0.18 Claude Code consolidation keep their
    # URLs working via stubs pointing at the new page.
    retired_groups = {
        "plugin-structure": (
            "Plugin Structure",
            "The Plugin Structure rules moved to the [Claude Code](claude.md) "
            "page when they gained their `claude-` prefixes in 0.18.0.",
        ),
        "command-format": (
            "Command Format",
            "The Command Format rules moved to the [Claude Code](claude.md) "
            "page when they gained their `claude-` prefixes in 0.18.0.",
        ),
        "marketplace": (
            "Marketplace",
            "The Marketplace rules moved to the [Claude Code](claude.md) "
            "page when they gained their `claude-` prefixes in 0.18.0.",
        ),
        "settings": (
            "Settings",
            "The Settings rules moved to the [Claude Code](claude.md) "
            "page when they gained their `claude-` prefixes in 0.18.0.",
        ),
        "rules-directory": (
            "Rules Directory",
            "The Rules Directory rules moved to the [Claude Code](claude.md) "
            "page when they gained their `claude-` prefixes in 0.18.0.",
        ),
        "skills-agents-hooks": (
            "Skills, Agents, Hooks",
            "This group was split up in 0.18.0: the hook rules live on the "
            "[Hooks](hooks.md) page, `claude-agent-frontmatter` moved to "
            "[Claude Code](claude.md), and `content-description-routing` to "
            "[Content Intelligence](content-intelligence.md).",
        ),
        "hidden-content": (
            "Hidden-Content Validation",
            "This group was renamed to [Security](security.md) in 0.18.0.",
        ),
    }
    for slug, (old_name, blurb) in retired_groups.items():
        stub = f"{GENERATED_HEADER}# {old_name}\n\n{blurb}\n"
        (rules_dir / f"{slug}.md").write_text(stub)
        print(f"  rules/{slug}.md (retired group stub)")

    # CLI reference
    (docs_dir / "cli.md").write_text(generate_cli_reference(commands))
    print("  cli.md")

    # Research page
    (docs_dir / "research.md").write_text(generate_research_page(research))
    print("  research.md")

    # Inject stats into index
    inject_stats(docs_dir / "index.md", rules_data)
    print("  index.md (stats injected)")

    # llms.txt endpoints — generated last: llms-full.txt reads the pages the
    # steps above just wrote to disk.
    coverage_errors = guides_coverage_errors(docs_dir)
    if coverage_errors:
        for err in coverage_errors:
            print(f"ERROR: {err}", file=sys.stderr)
        sys.exit(1)

    write_llms_outputs(docs_dir, rules_data)

    print(f"\nDone. Generated site content for skillsaw v{__version__}.")


if __name__ == "__main__":
    main()
