#!/usr/bin/env python3
"""Publish GitHub release notes from `gh api --paginate --slurp` JSON.

The generated Markdown is committed so local site builds work offline.
Pages CI refreshes it before every build, including on release events.
"""

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HEADER = "<!-- Generated by scripts/generate-changelog.py — do not edit by hand -->\n\n"


def generate(release_pages, docs):
    """Render public releases newest-first, preserving their published Markdown."""
    releases = sorted(
        (release for page in release_pages for release in page if not release["draft"]),
        key=lambda release: release["published_at"],
        reverse=True,
    )
    # Validate every filename before changing any output.
    for release in releases:
        if not re.fullmatch(r"v?\d+\.\d+\.\d+(?:[-+][A-Za-z0-9.-]+)?", release["tag_name"]):
            raise ValueError(f"Unsupported release tag: {release['tag_name']!r}")
    destination = docs / "changelog"
    destination.mkdir(exist_ok=True)
    for old in destination.glob("*.md"):
        if old.read_text().startswith(HEADER):
            old.unlink()
    index = [HEADER + "# Changelog", "Release notes for every published skillsaw release.", ""]
    for release in releases:
        version = release["tag_name"].removeprefix("v")
        date = release["published_at"][:10]
        prerelease = " · Pre-release" if release["prerelease"] else ""
        index.append(f"- [{version}](changelog/{version}.md) — {date}{prerelease}")
        content = (
            f"{HEADER}# {version}\n\n"
            f"{date}{prerelease} · [View on GitHub]({release['html_url']})\n\n"
            f"{(release['body'] or 'No release notes were provided.').strip()}\n"
        )
        if version == "0.20.0":
            content += "\n" + (docs / "includes" / "upgrading-0.20.md").read_text()
        (destination / f"{version}.md").write_text(content)
    (docs / "changelog.md").write_text("\n\n".join(index[:2]) + "\n" + "\n".join(index[2:]) + "\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("releases", type=Path, help="JSON from gh api --paginate --slurp")
    args = parser.parse_args()
    generate(json.loads(args.releases.read_text()), ROOT / "docs")


if __name__ == "__main__":
    main()
