name: Test Action Review

on:
  workflow_run:
    workflows: ["Test Action"]
    types: [completed]

jobs:
  review:
    if: github.event.workflow_run.event == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v5

      - uses: ./review
