name: Test Action

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  self-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: ./
        with:
          strict: true
